import { Question } from './types';

export const data: Question[] = [
  { norwegian: 'tale', english: 'speech' },
  { norwegian: 'formidle', english: 'convey' },
  { norwegian: 'muntlig', english: 'oral' },
  { norwegian: 'arbeidslivsbalanse', english: 'work life balance' },
  { norwegian: 'å sørge for', english: 'to ensure' },
  { norwegian: 'forhandle', english: 'negotiate' },
  { norwegian: 'lønnsnivå', english: 'salary level' },
  { norwegian: 'arbeidsgiver', english: 'employer' },
  { norwegian: 'enighet', english: 'agreement' },
  { norwegian: 'sluttpakke', english: 'severance package' },
  { norwegian: 'å tilby', english: 'to offer' },
  { norwegian: 'frivillig', english: 'voluntary' },
  { norwegian: 'nedbemannet', english: 'downsized' },
  { norwegian: 'deltid', english: 'part time' },
  { norwegian: 'tilsyn', english: 'supervision' },
  { norwegian: 'faste arbeidstider', english: 'fixed working hours' },
  {
    norwegian: 'tilpasse start- og sluttidspunkt',
    english: 'adjust the start and end time',
  },
  { norwegian: 'frihet', english: 'freedom' },
  { norwegian: 'yrke', english: 'profession' },
  { norwegian: 'yrkesetikk', english: 'professional ethics' },
  { norwegian: 'faglige', english: 'professional' },
  { norwegian: 'bestemt,spesifikk', english: 'specific' },
  { norwegian: 'prinsipp', english: 'principle' },
  { norwegian: 'atferd,oppførsel', english: 'behavior' },
  { norwegian: 'fysiske', english: 'physical' },
  { norwegian: 'å forsinke', english: 'to delay' },
  { norwegian: 'å utsett', english: 'to postpone' },
  { norwegian: 'å delegere', english: 'to delegate' },
  { norwegian: 'medarbeidergjennomgang', english: 'employee review' },
  { norwegian: 'langsiktige', english: 'long-term' },
  { norwegian: 'tidsrammer', english: 'timeframes' },
  { norwegian: 'kjerne', english: 'core' },
  { norwegian: 'grunnleggende', english: 'basic' },
  { norwegian: 'unike', english: 'unique' },
  { norwegian: 'utstyr', english: 'equipment' },
  { norwegian: 'å opprette', english: 'to establish' },
  { norwegian: 'formell', english: 'formal' },
  { norwegian: 'å vedlikeholde', english: 'to maintain' },
  { norwegian: 'kunnskaper', english: 'knowledge' },
  { norwegian: 'karrierevekst', english: 'career growth' },
  { norwegian: 'tverrkulturelt', english: 'cross-culturally' },
  { norwegian: 'å samarbeide', english: 'to cooperate, collaborate' },
  { norwegian: 'bakgrunner', english: 'background' },
  { norwegian: 'å bestemme,å avgjøre', english: 'to decide' },
  { norwegian: 'konfliktløsning', english: 'conflict resolution' },
  { norwegian: 'uenigheter', english: 'disagreements' },
  { norwegian: 'erfaring', english: 'experience' },
  { norwegian: 'oppleve,erfaren', english: 'experienced' },
  { norwegian: 'veiledning', english: 'guidance' },
  { norwegian: 'støtte', english: 'support' },
  { norwegian: 'å overvåke', english: 'to supervise, to monitor' },
  { norwegian: 'kunnskapsoverføring', english: 'knowledge transfer' },
  { norwegian: 'ledelse', english: 'management' },
  { norwegian: 'å holde seg', english: 'to hold on' },
  { norwegian: 'fagfelt', english: 'professional field' },
  { norwegian: 'stil', english: 'style' },
  { norwegian: 'å foretrekke', english: 'to prefer' },
  { norwegian: 'tidsstyring', english: 'time management' },
  { norwegian: 'å maksimere', english: 'to maximize' },
  { norwegian: 'yrkesmessa', english: 'vocational fair' },
  { norwegian: 'å skifte', english: 'to replace' },
  { norwegian: 'å oppnå', english: 'to achieve' },
  { norwegian: 'tilnærming', english: 'approach' },
  { norwegian: 'aspekter', english: 'aspects' },
  { norwegian: 'endringer', english: 'changes' },
  { norwegian: 'målrettet', english: 'targeted' },
  { norwegian: 'kan oppnås', english: 'can be achieved' },
  { norwegian: 'ansvar', english: 'responsibility' },
  { norwegian: 'ansvarliggjøring', english: 'accountability' },
  { norwegian: 'ansvarlige', english: 'responsible' },
  { norwegian: 'handlinger og resultater', english: 'actions and results' },
  { norwegian: 'å overføre', english: 'to transfer' },
  { norwegian: 'inkluderende', english: 'inclusive' },
  { norwegian: 'mangfold', english: 'diversity' },
  { norwegian: 'verdsetter,verdier', english: 'values' },
  { norwegian: 'sosiale arrangementer', english: 'social events' },
  { norwegian: 'myndighet,autoritet', english: 'authority' },
  { norwegian: 'retningslinjer', english: 'guidelines' },
  { norwegian: 'beslutning', english: 'decision' },
  { norwegian: 'innenfor', english: 'within' },
  { norwegian: 'arbeidstakerdeltakelse', english: 'employee participation' },
  { norwegian: 'å delta', english: 'to attend, to participate' },
  { norwegian: 'rette', english: 'correct' },
  { norwegian: 'å fremme', english: 'promoting' },
  { norwegian: 'arbeidstakerdeltakelse', english: 'employee participation' },
  { norwegian: 'å oppmuntre til', english: 'to encourage' },
  { norwegian: 'oppmuntre', english: 'encourage' },
  { norwegian: 'oppmuntret', english: 'encouraged' },
  { norwegian: 'utelukkende', english: 'exclusively' },
  { norwegian: 'å lage', english: 'to create' },
  {
    norwegian: 'å understreke prestasjon, å vektlegge oppnåelse',
    english: 'to emphasize achievement',
  },
  { norwegian: 'forslag', english: 'suggestion' },
  { norwegian: 'uforanderlig arbeidstid', english: 'unchanging working hours' },
  { norwegian: 'å tilby', english: 'offering' },
  { norwegian: 'arbeidsordninger', english: 'work arrangements' },
  { norwegian: 'tilpasser seg', english: 'adapts' },
  { norwegian: 'behov', english: 'need' },
  { norwegian: 'å ivareta', english: 'to preserve' },
  { norwegian: 'å ta hensyn til,å overveie', english: 'to consider' },
  { norwegian: 'plasseringen', english: 'the location' },
  { norwegian: 'behandler', english: 'treats' },
  { norwegian: 'samhandler', english: 'interacts' },
  {
    norwegian: 'å utøve godt lederskap',
    english: 'to exercise good leadership',
  },
  { norwegian: 'felles', english: 'common' },
  { norwegian: 'veilede', english: 'guide' },
  { norwegian: 'veileder', english: 'supervisor' },
  { norwegian: 'emner', english: 'subjects' },
  { norwegian: 'utfordringer', english: 'challenges' },
  { norwegian: 'å fremme', english: 'to promote' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'ærlighet', english: 'honesty' },
  { norwegian: 'verdsatt', english: 'appreciated' },
  { norwegian: 'søke', english: 'seek' },
  { norwegian: 'skritt', english: 'steps' },
  { norwegian: 'selvstendig', english: 'independent' },
  { norwegian: 'selvstendige', english: 'independent' },
  { norwegian: 'utvide', english: 'expand' },
  { norwegian: 'i henhold til', english: 'according to' },
  { norwegian: 'å handle', english: 'to act, to shop' },
  { norwegian: 'handler', english: 'acts' },
  { norwegian: 'beslutninger', english: 'decisions' },
  { norwegian: 'utveksling', english: 'exchange' },
  { norwegian: 'å bidra', english: 'to contribute' },
  { norwegian: 'å håndtere', english: 'to handle, to manage' },
  { norwegian: 'frist', english: 'deadline' },
  { norwegian: 'tidsfrister', english: 'deadlines' },
  { norwegian: 'pålitelighet,pålitelig', english: 'reliable' },
  { norwegian: 'vesentlige', english: 'significant' },
  { norwegian: 'årsaker', english: 'causes' },
  { norwegian: 'passende', english: 'appropriate' },
  { norwegian: 'oppdaget', english: 'discovered' },
  { norwegian: 'å årsake', english: 'to cause' },
  { norwegian: 'å passe', english: 'to fit' },
  { norwegian: 'å oppdage', english: 'to discover' },
  { norwegian: 'å foreslå', english: 'to suggest' },
  { norwegian: 'å forbedre', english: 'to improve' },
  { norwegian: 'å uttrykke', english: 'to express' },
  { norwegian: 'å forlate', english: 'to leave' },
  { norwegian: 'å oppfordre', english: 'to urge' },
  { norwegian: 'å øke', english: 'to increase' },
  { norwegian: 'økt', english: 'increased' },
  { norwegian: 'utfordringer', english: 'challenges' },
  { norwegian: 'ansvar', english: 'responsibility' },
  { norwegian: 'ansvarlighet', english: 'responsibility' },
  { norwegian: 'ansvarlig', english: 'responsible' },
  { norwegian: 'hard', english: 'hard' },
  { norwegian: 'å fullføre', english: 'to complete' },
  { norwegian: 'utsatt', english: 'postponed' },
  { norwegian: 'forslag', english: 'proposal' },
  { norwegian: 'virdering', english: 'assessment' },
  { norwegian: 'vurdere', english: 'consider' },
  { norwegian: 'støtte', english: 'support' },
  { norwegian: 'utforske', english: 'explore' },
  { norwegian: 'ressursene', english: 'the resources' },
  { norwegian: 'ressurser', english: 'resources' },
  { norwegian: 'begrenset', english: 'limited' },
  { norwegian: 'å justere', english: 'to adjust' },
  { norwegian: 'behov', english: 'needs' },
  { norwegian: 'milepæl', english: 'milestone' },
  { norwegian: 'nådd', english: 'reached' },
  { norwegian: 'formidle', english: 'convey, communicate' },
  { norwegian: 'unngå', english: 'avoid' },
  { norwegian: 'nødvendig', english: 'necessary' },
  { norwegian: 'regelmessige', english: 'regular' },
  { norwegian: 'oppdrag', english: 'assignment' },
  { norwegian: 'klarhet', english: 'clarity' },
  { norwegian: 'ærlig', english: 'honesty' },
  { norwegian: 'å forberede seg', english: 'to prepare oneself' },
  { norwegian: 'vedlikehold', english: 'maintenance' },
  { norwegian: 'regelmessig', english: 'regularly' },
  { norwegian: 'egenskap', english: 'trait, quality' },
  { norwegian: 'vurdere', english: 'consider, assess' },
  { norwegian: 'fremgang', english: 'progress' },
  { norwegian: 'ferdigheter', english: 'skills' },
  { norwegian: 'ferdighetene', english: 'the skills' },
  { norwegian: 'avbryt', english: 'cancel' },
  { norwegian: 'forsette', english: 'continue' },
  { norwegian: 'skrivere', english: 'printer' },
  { norwegian: 'ved', english: 'by' },
  { norwegian: 'opplevelse', english: 'experience' },
  { norwegian: 'ytelse', english: 'performance' },
  { norwegian: 'fremfor', english: 'over' },
  { norwegian: 'utseende', english: 'look' },
  { norwegian: 'sammenheng', english: 'context' },
  { norwegian: 'tiltaleform', english: 'form of indictment' },
  { norwegian: 'overordnet', english: 'superior' },
  { norwegian: 'innebærer', english: 'implies' },
  { norwegian: 'overarbeid', english: 'overtime' },
  { norwegian: 'medarbeidersamtale', english: 'employee interview' },
  { norwegian: 'nettarbeid', english: 'computer work' },
  { norwegian: 'å utføre', english: 'to perform' },
  { norwegian: 'utføres', english: 'is performed, is carried out' },
  { norwegian: 'å forklare', english: 'to explain' },
  { norwegian: 'begrep', english: 'term' },
  { norwegian: 'å styrke', english: 'to strengthen' },
  { norwegian: 'forhold', english: 'relationship' },
  { norwegian: 'å overføre', english: 'to transfer' },
  { norwegian: 'lønnsøkning', english: 'salary increase' },
  { norwegian: 'stillingsbeskrivelse', english: 'job description' },
  { norwegian: 'ansvarsområder', english: 'areas of responsibility' },
  { norwegian: 'avdeling', english: 'department' },
  { norwegian: 'avdelinger', english: 'departments' },
  { norwegian: 'åpent kontorlandskap', english: 'open office landscape' },
  { norwegian: 'tariffavtale', english: 'collective agreement' },
  { norwegian: 'arbeidsforhold', english: 'working conditions' },
  { norwegian: 'forening', english: 'union,association' },
  { norwegian: 'verdier,verdsetter', english: 'values' },
  { norwegian: 'å styre', english: 'to control' },
  { norwegian: 'styrer', english: 'controls' },
  { norwegian: 'verdsatt', english: 'appreciated' },
  { norwegian: 'utføre', english: 'perform' },
  { norwegian: 'forvalte', english: 'manage,maintain' },
  { norwegian: 'tidsforvaltning', english: 'time management' },
  { norwegian: 'forutseende', english: 'anticipatory' },
  { norwegian: 'establish', english: 'etablere' },
  { norwegian: 'anerkjennelse', english: 'recognition' },
  { norwegian: 'knyttet', english: 'attached' },
  { norwegian: 'arbeidsytelse', english: 'work performance' },
  { norwegian: 'medarbeider,ansatte', english: 'employee,co-worker' },
  { norwegian: 'undersøkelse', english: 'exam,survey' },
  { norwegian: 'medarbeiderundersøkelse', english: 'employee survey' },
  { norwegian: 'kunde', english: 'customer' },
  { norwegian: 'tilfredshet', english: 'satisfaction' },
  { norwegian: 'kundetilfredshet', english: 'customer satisfaction' },
  { norwegian: 'innsats', english: 'efforts' },
  { norwegian: 'stramt', english: 'tight' },
  { norwegian: 'frist', english: 'deadline' },
  { norwegian: 'krav', english: 'requirement,demand' },
  { norwegian: 'krav', english: 'requirements,demands' },
  { norwegian: 'kravet', english: 'the requirement' },
  { norwegian: 'kravene', english: 'the requirements' },
  { norwegian: 'likestilling', english: 'equality' },
  { norwegian: 'har like', english: 'have equal' },
  { norwegian: 'rettferdig', english: 'fairly' },
  {
    norwegian: 'kjønn, alder, etnisitet osv.',
    english: 'gender, age, ethnicity, etc.',
  },
  { norwegian: 'evne', english: 'skill' },
  { norwegian: 'evnen', english: 'the ability' },
  { norwegian: 'tykkere', english: 'thicker' },
  { norwegian: 'vaskemidler', english: 'detergents' },
  { norwegian: 'vifte', english: 'fan' },
  { norwegian: 'gardiner', english: 'curtains' },
  { norwegian: 'la kranen renne', english: 'let the faucet run' },
  { norwegian: 'oppvaskmaskin', english: 'dishwasher' },
  { norwegian: 'hastighet,fart', english: 'speed' },
  { norwegian: 'søppelkasse', english: 'trash can' },
  { norwegian: 'estetikk', english: 'aesthetics' },
  { norwegian: 'trivsel', english: 'well being' },
  { norwegian: 'uorganiserte', english: 'disorganized' },
  { norwegian: 'overfylte med ting', english: 'cluttered' },
  { norwegian: 'å skape', english: 'to create' },
  { norwegian: 'innbydende atmosfære', english: 'welcoming atmosphere' },
  { norwegian: 'lukkede', english: 'closed' },
  { norwegian: 'hyppig,hyppige', english: 'frequent' },
  { norwegian: 'arter', english: 'species' },
  { norwegian: 'å kreve', english: 'to demand, require' },
  { norwegian: 'laveste', english: 'lowest' },
  { norwegian: 'fylt', english: 'filled' },
  { norwegian: 'fult', english: 'full' },
  { norwegian: 'overflater', english: 'surfaces' },
  { norwegian: 'synlig', english: 'visible' },
  { norwegian: 'skitt', english: 'dirt' },
  { norwegian: 'kjøkkenutstyr', english: 'kitchen utensils' },
  { norwegian: 'å desinfisere', english: 'to disinfect' },
  { norwegian: 'i tillegg til', english: 'in addition to' },
  { norwegian: 'komfortabelt', english: 'comfortable' },
  { norwegian: 'avslappende', english: 'relaxing' },
  { norwegian: 'slå', english: 'turn' },
  { norwegian: 'slå av', english: 'turn off' },
  { norwegian: 'slå på', english: 'turn on' },
  { norwegian: 'slått på, skrudd på', english: 'turned on' },
  { norwegian: 'beroligende', english: 'calming,soothing' },
  { norwegian: 'å oppbevare', english: 'to store,keep' },
  { norwegian: 'utstyr', english: 'equipment' },
  { norwegian: 'hjern', english: 'brain' },
  { norwegian: 'hjernen', english: 'the brain' },
  { norwegian: 'luftkvaliteten', english: 'the air quality' },
  { norwegian: 'luftfuktere', english: 'humidifiers' },
  { norwegian: 'å tilføre,å legge til', english: 'to add' },
  { norwegian: 'inneluft', english: 'indoor air' },
  { norwegian: 'levetiden', english: 'the life time' },
  { norwegian: 'å overbelaste', english: 'to overload' },
  { norwegian: 'produsenten', english: 'the manufacturer' },
  { norwegian: 'blant', english: 'among' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'å innføre,introdusere', english: 'to introduce' },
  { norwegian: 'strømregninger', english: 'electricity bills' },
  { norwegian: 'strømsparemodus', english: 'power saving mode' },
  { norwegian: 'vannbesparende', english: 'water saving' },
  { norwegian: 'dusjhode', english: 'shower head' },
  { norwegian: 'programmerbare', english: 'programmable' },
  { norwegian: 'termostater', english: 'thermostats' },
  { norwegian: 'kilder', english: 'sources' },
  { norwegian: 'mur,vegg', english: 'wall' },
  { norwegian: 'lydisolerende', english: 'soundproofing' },
  { norwegian: 'vant til', english: 'used to' },
  { norwegian: 'å bevare', english: 'to preserve' },
  { norwegian: 'stille', english: 'quiet' },
  { norwegian: 'å stille inn', english: 'to set in' },
  { norwegian: 'matvarer', english: 'foodstuffs,food' },
  { norwegian: 'å vaske klær', english: 'to do laundry' },
  { norwegian: 'stoff', english: 'fabric' },
  { norwegian: 'avstengningsventil', english: 'shut-off valve' },
  { norwegian: 'bøtte', english: 'bucket' },
  { norwegian: 'svamp', english: 'sponge' },
  { norwegian: 'etterfulgt', english: 'followed' },
  { norwegian: 'skylling', english: 'rinse' },
  {
    norwegian: 'hjemmeunderholdningssystem',
    english: 'home entertainment system',
  },
  { norwegian: 'tilgang', english: 'access' },
  { norwegian: 'å beholde,å holde', english: 'to retain,to keep' },
  { norwegian: 'fuktigheten', english: 'the humidity' },
  { norwegian: 'fuktighet', english: 'moisture' },
  { norwegian: 'kjølig', english: 'cool' },
  { norwegian: 'luftforurensning', english: 'air pollution' },
  { norwegian: 'rengjøringsprodukter', english: 'cleaning products' },
  { norwegian: 'å lufte ut', english: 'to air out,ventilate' },
  { norwegian: 'å forlenge', english: 'to extend,prolong' },
  { norwegian: 'slitasje', english: 'wear and tear' },
  { norwegian: 'påslått', english: 'switched on' },
  { norwegian: 'påslåing', english: 'switching on' },
  { norwegian: 'støvfrie', english: 'dust free' },
  { norwegian: 'overoppheting', english: 'overheating' },
  { norwegian: 'fuktige', english: 'moist' },
  { norwegian: 'lader kontinuerlig', english: 'charging continuously' },
  { norwegian: 'å fremskynde', english: 'to speed up' },
  { norwegian: 'kraftig', english: 'powerful' },
  { norwegian: 'stråle', english: 'jet' },
  { norwegian: 'matrester', english: 'leftover food' },
  { norwegian: 'kjeller', english: 'basement' },
  { norwegian: 'mugg', english: 'mold' },
  { norwegian: 'avfukter', english: 'dehumidifier' },
  { norwegian: 'nødvendig', english: 'necessary' },
  { norwegian: 'oppvask', english: 'dishes' },
  { norwegian: 'oppvasken', english: 'the dishes' },
  { norwegian: 'cycles', english: 'sykluser' },
  { norwegian: 'nivå', english: 'level' },
  { norwegian: 'lydnivået', english: 'the sound level' },
  { norwegian: 'å motvirke', english: 'to counteract' },
  { norwegian: 'gulvflater', english: 'floor surfaces' },
  { norwegian: 'teppe', english: 'carpet' },
  { norwegian: 'myke', english: 'soft' },
  { norwegian: 'møbler', english: 'furniture' },
  { norwegian: 'lokk', english: 'lid' },
  { norwegian: 'gryte og pann', english: 'pot and pan' },
  { norwegian: 'vannbesparelse', english: 'water saving' },
  { norwegian: 'lavt-flyt', english: 'low flow' },
  { norwegian: 'engasjerende', english: 'engaging' },
  { norwegian: 'vaskeliste', english: 'laundry list' },
  { norwegian: 'belønninger', english: 'rewards' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'a utføre', english: 'to carry out' },
  { norwegian: 'utfører', english: 'performs' },
  { norwegian: 'ulike', english: 'different' },
  { norwegian: 'husarbeidsoppgaver', english: 'housework tasks' },
  { norwegian: 'tidskrevende', english: 'time consuming' },
  { norwegian: 'bærekraftige', english: 'sustainable' },
  { norwegian: 'oppsett', english: 'setup' },
  { norwegian: 'samtidig', english: 'simultaneous' },
  { norwegian: 'økt', english: 'increased' },
  { norwegian: 'å håndtere', english: 'to manage, to handle' },
  { norwegian: 'påvirkning', english: 'impact' },
  { norwegian: 'emballasje', english: 'packaging' },
  { norwegian: 'å sortere', english: 'to sort' },
  { norwegian: 'etablere', english: 'establish' },
  { norwegian: 'ved', english: 'by' },
  { norwegian: 'lytte', english: 'listen' },
  { norwegian: 'badekar', english: 'bathtub' },
  { norwegian: 'lengden', english: 'the length' },
  { norwegian: 'opplevelse', english: 'experience' },
  { norwegian: 'høyttaler', english: 'speaker' },
  { norwegian: 'kontinuerlig', english: 'continuously' },
  { norwegian: 'å sette,å plasse', english: 'to place' },
  { norwegian: 'midt', english: 'middle' },
  { norwegian: 'belysning', english: 'lighting' },
  { norwegian: 'lommelykt', english: 'flashlight' },
  { norwegian: 'å innrede', english: 'to furnish' },
  { norwegian: 'å tørke', english: 'to dry' },
  { norwegian: 'tørr', english: 'dry' },
  { norwegian: 'sørge', english: 'ensure, keep, provide' },
  { norwegian: 'lyspærer', english: 'light bulbs' },
  { norwegian: 'husarbeid', english: 'housework' },
  { norwegian: 'å håndtere', english: 'to handle' },
  { norwegian: 'matavfall', english: 'food waste' },
  { norwegian: 'kraner', english: 'taps, faucets' },
  { norwegian: 'kortere', english: 'shorter' },
  { norwegian: 'enheter', english: 'devices,units' },
  { norwegian: 'enheten', english: 'the device,the unit' },
  { norwegian: 'enhetene', english: 'the devices, the units' },
  { norwegian: 'påslått', english: 'switched on' },
  { norwegian: 'matbutikken', english: 'the grocery store' },
  { norwegian: 'engangsplastposer', english: 'disposable plastic bags' },
  { norwegian: 'forventer', english: 'expects' },
  { norwegian: 'samle opp', english: 'pick up' },
  { norwegian: 'rot', english: 'mess' },
  { norwegian: 'rengjøre og rydde', english: 'clean and clear' },
  { norwegian: 'på forhånd', english: 'in advance' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'begrense', english: 'restrict, limit' },
  { norwegian: 'skape', english: 'create' },
  { norwegian: 'skade', english: 'damage' },
  { norwegian: 'ødelagt', english: 'destroyed' },
  { norwegian: 'ærlig', english: 'honest' },
  { norwegian: 'ærlighet', english: 'honesty' },
  { norwegian: 'sikkerhet', english: 'safety' },
  { norwegian: 'trygt', english: 'safe' },
  { norwegian: 'ta vare på deg selv', english: 'take care of yourself' },
  { norwegian: 'vær forsiktig', english: 'be careful' },
  { norwegian: 'ulåste', english: 'unlocked' },
  { norwegian: 'låst', english: 'locked' },
  { norwegian: 'røykvarsler', english: 'smoke alarm' },
  { norwegian: 'sikkerhetssystem', english: 'security system' },
  { norwegian: 'sjelden', english: 'rarely' },
  { norwegian: 'framtid,fremtid', english: 'future' },
  { norwegian: 'framover,fremover', english: 'forwards' },
  { norwegian: 'på forhånd', english: 'in advance' },
  { norwegian: 'alder', english: 'age' },
  { norwegian: 'ovner', english: 'furnace, heater, ovens' },
  { norwegian: 'isolere', english: 'isolate, insulate' },
  { norwegian: 'beslutningen', english: 'the decision' },
  { norwegian: 'til slutt', english: 'in the end' },
  { norwegian: 'inngrep', english: 'interventions' },
  { norwegian: 'lagring', english: 'storage' },
  { norwegian: 'komplisert', english: 'complicated' },
  { norwegian: 'resirkulering', english: 'recycling' },
  { norwegian: 'resirkulere', english: 'recycle' },
  { norwegian: 'erstatte', english: 'replace' },
  { norwegian: 'gjenbrukbare', english: 'reusable' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'sunn,sunt', english: 'healthy' },
  { norwegian: 'matlaging', english: 'cooking' },
  { norwegian: 'ferske', english: 'fresh' },
  { norwegian: 'ferdigmat', english: 'ready meals' },
  { norwegian: 'uavhengig', english: 'regardless,independent' },
  { norwegian: 'lesing', english: 'reading' },
  { norwegian: 'tilgjengelig', english: 'available' },
  { norwegian: 'rekke', english: 'variety' },
  { norwegian: 'felles', english: 'common' },
  { norwegian: 'rot', english: 'clutter' },
  { norwegian: 'å forvalte', english: 'to manage' },
  { norwegian: 'utgifter', english: 'expenses' },
  { norwegian: 'inntekter', english: 'income' },
  { norwegian: 'følge', english: 'follow' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'luksus', english: 'luxury' },
  { norwegian: 'varer', english: 'items, goods' },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'livsstil', english: 'lifestyle' },
  { norwegian: 'gjenbruke', english: 'reuse' },
  { norwegian: 'modus', english: 'mode' },
  { norwegian: 'husholdningen', english: 'the household' },
  { norwegian: 'barnegrinder', english: 'childsgate' },
  { norwegian: 'sikkerhetsutstyr', english: 'safety devices' },
  { norwegian: 'rengjøringsmidler', english: 'cleaning agents' },
  { norwegian: 'gjenstander', english: 'objects' },
  { norwegian: 'husholdningsartikler', english: 'household items' },
  { norwegian: 'erstattes', english: 'is replaced' },
  { norwegian: 'å fremme', english: 'to promote' },
  { norwegian: 'regelmessig', english: 'regularly' },
  { norwegian: 'kosthold', english: 'diet' },
  { norwegian: 'mengder', english: 'amounts, quantities' },
  { norwegian: 'umiddelbart', english: 'immediately' },
  { norwegian: 'fryser', english: 'freezer' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'luftrenser', english: 'air cleaner' },
  { norwegian: 'ferdigheter', english: 'skills' },
  { norwegian: 'reparasjoner', english: 'repairs' },
  { norwegian: 'ryddigere', english: 'tidier' },
  { norwegian: 'badet', english: 'the bathroom' },
  { norwegian: 'bad', english: 'bathroom' },
  { norwegian: 'grundig', english: 'thoroughly' },
  { norwegian: 'å samle', english: 'to collect,to gather' },
  { norwegian: 'ubrukt', english: 'unused' },
  { norwegian: 'støy,bråk', english: 'noise' },
  { norwegian: 'å dekke', english: 'to cover' },
  { norwegian: 'lyder', english: 'sounds' },
  { norwegian: 'tykk', english: 'thick' },
  { norwegian: 'handler klær', english: 'shopping for clothes' },
  { norwegian: 'å vurdere', english: 'to consider' },
  { norwegian: 'å sikre', english: 'to secure' },
  { norwegian: 'noe som passer godt', english: 'something that fits well' },
  { norwegian: 'størrelse', english: 'size' },
  { norwegian: 'god passform', english: 'good fit' },
  { norwegian: 'utelukkende', english: 'exclusively' },
  { norwegian: 'merke', english: 'mark' },
  { norwegian: 'trender', english: 'trends' },
  { norwegian: 'størrelsesetiketter', english: 'size labels' },
  { norwegian: 'dyreste', english: 'most expensive' },
  { norwegian: 'uavhengig', english: 'regardless' },
  { norwegian: 'handlevogn', english: 'shopping cart' },
  { norwegian: 'gjenstander', english: 'objects' },
  { norwegian: 'et vare', english: 'an item' },
  { norwegian: 'fasthet', english: 'firmness' },
  { norwegian: 'skadet', english: 'hurt' },
  { norwegian: 'moden', english: 'ripe,mature' },
  { norwegian: 'overmoden', english: 'overripe' },
  { norwegian: 'bestill', english: 'order' },
  { norwegian: 'forrett', english: 'appetizer' },
  { norwegian: 'hovedrett', english: 'main course' },
  { norwegian: 'matopplevelse', english: 'dining experience' },
  { norwegian: 'en rett', english: 'a dish' },
  { norwegian: 'gjett', english: 'guess' },
  { norwegian: 'vanligvis', english: 'usually' },
  { norwegian: 'fysiske', english: 'physical' },
  { norwegian: 'plagg', english: 'garment' },
  { norwegian: 'å sammenligne', english: 'to compare' },
  { norwegian: 'kvalitetsråvarer', english: 'quality raw materials' },
  { norwegian: 'utløpsdatoer', english: 'expiration dates' },
  { norwegian: 'friskhet', english: 'freshness' },
  { norwegian: 'utseende', english: 'appearance' },
  { norwegian: 'hermetiserte', english: 'canned' },
  { norwegian: 'varer', english: 'goods' },
  { norwegian: 'hylle', english: 'shelf' },
  { norwegian: 'matforgiftning', english: 'food poisoning' },
  { norwegian: 'å tilberede et måltid', english: 'to prepare a meal' },
  { norwegian: 'a forberede', english: 'to prepare' },
  { norwegian: 'skjærebrett', english: 'cutting board' },
  { norwegian: 'kjøkkenutstyr', english: 'kitchen utensils' },
  { norwegian: 'moten', english: 'the fashion' },
  { norwegian: 'tidkrevende', english: 'time consuming' },
  { norwegian: 'oppskrifter', english: 'recipes' },
  { norwegian: 'ferskhet', english: 'freshness' },
  { norwegian: 'tegn', english: 'signs' },
  { norwegian: 'kanter', english: 'edges' },
  { norwegian: 'risikoen', english: 'the risk' },
  { norwegian: 'ved berøring', english: 'by touch' },
  { norwegian: 'matvarer', english: 'foodstuffs' },
  { norwegian: 'matsvinn', english: 'food waste' },
  { norwegian: 'mengder', english: 'amounts' },
  { norwegian: 'kvantumsrabatt', english: 'quantity discount' },
  { norwegian: 'uavhengig', english: 'independent' },
  { norwegian: 'holdbarheten', english: 'durability,shelf life' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'oppbevaringskrav', english: 'storage requirements' },
  { norwegian: 'øverste hyllene', english: 'top shelves' },
  { norwegian: 'anmeldelser', english: 'reviews' },
  { norwegian: 'kundeanmeldelser', english: 'customer reviews' },
  { norwegian: 'anbefalinger', english: 'recommendations' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'kjedesteder', english: 'chain locations' },
  { norwegian: 'tilnærming', english: 'approach' },
  { norwegian: 'sunne', english: 'healthy' },
  { norwegian: 'alternativer', english: 'options' },
  { norwegian: 'næringsinformasjonen', english: 'the nutritional information' },
  { norwegian: 'uansett', english: 'regardless' },
  { norwegian: 'sjanser', english: 'chances' },
  { norwegian: 'varige', english: 'lasting' },
  { norwegian: 'investeringer', english: 'investments' },
  { norwegian: 'luksusmerker', english: 'luxury brands' },
  {
    norwegian: 'meld deg på nyhetsbrev',
    english: 'sign up for the newsletter',
  },
  { norwegian: 'ved å være', english: 'by being' },
  { norwegian: 'billig', english: 'cheap' },
  { norwegian: 'mengde', english: 'quantity' },
  { norwegian: 'plastavfall', english: 'plastic waste' },
  { norwegian: 'dagligvarer', english: 'groceries' },
  { norwegian: 'hermetikk', english: 'canned' },
  { norwegian: 'unødvendig', english: 'unnecessary' },
  { norwegian: 'plastemballasjer', english: 'plastic packaging' },
  { norwegian: 'fordele', english: 'advantage,benefit' },
  { norwegian: 'fordeler', english: 'benefits,advantages' },
  { norwegian: 'fordelene', english: 'the benefits' },
  { norwegian: 'bevaring', english: 'conservation,preservation,retention' },
  { norwegian: 'holdbarhet', english: 'shelf life' },
  { norwegian: 'inneholder', english: 'contains' },
  { norwegian: 'konserveringsmidler', english: 'preservatives' },
  { norwegian: 'ulike', english: 'different' },
  { norwegian: 'utgitt', english: 'released' },
  {
    norwegian: 'utseende og popularitet',
    english: 'appearance and popularity',
  },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'kunstige', english: 'artificial' },
  { norwegian: 'motetrender', english: 'fashion trends' },
  { norwegian: 'kleskjeder', english: 'clothing chains' },
  { norwegian: 'når det gjelder', english: 'when it comes to' },
  { norwegian: 'impulskjøp', english: 'impulse buy' },
  { norwegian: 'kvantumsrabatter', english: 'quantity discounts' },
  { norwegian: 'hurtigmat', english: 'fast food' },
  { norwegian: 'innhold', english: 'content' },
  { norwegian: 'næringsinnhold', english: 'nutritional content' },
  { norwegian: 'lavt fett', english: 'low fat' },
  { norwegian: 'rimelig', english: 'reasonable,affordable' },
  { norwegian: 'skinnende', english: 'shiny' },
  { norwegian: 'gjeller', english: 'gills' },
  { norwegian: 'skinn', english: 'leather' },
  { norwegian: 'stoff', english: 'fabric' },
  { norwegian: 'skall', english: 'shell' },
  { norwegian: 'utsikt', english: 'view' },
  { norwegian: 'utmerket', english: 'excellent' },
  { norwegian: 'vennligst', english: 'please' },
  { norwegian: 'vanntette,vanntett materiale', english: 'waterproof' },
  { norwegian: 'ull', english: 'wool' },
  { norwegian: 'fullkornsbrød', english: 'whole grain bread' },
  { norwegian: 'glutenfritt', english: 'gluten free' },
  { norwegian: 'kart', english: 'map' },
  { norwegian: 'meieri', english: 'dairy' },
  { norwegian: 'koffeinfri', english: 'decaffeinated' },
  { norwegian: 'innkvartere', english: 'accommodate' },
  { norwegian: 'importert', english: 'imported' },
  { norwegian: 'fettfattige', english: 'low fat' },
  { norwegian: 'geitemelk', english: "goat's milk" },
  { norwegian: 'guidede', english: 'guided' },
  { norwegian: 'skjerf', english: 'scarf' },
  { norwegian: 'opphold', english: 'stay' },
  { norwegian: 'forlenge', english: 'extend' },
  { norwegian: 'krydret', english: 'spiced' },
  { norwegian: 'stark', english: 'spicy' },
  { norwegian: 'kasjmir', english: 'cashmere' },
  { norwegian: 'skivet', english: 'sliced' },
  { norwegian: 'kjole', english: 'dress' },
  { norwegian: 'flytende', english: 'fluid' },
  { norwegian: 'økologisk', english: 'ecological,organic' },
  { norwegian: 'svømmebassenget', english: 'the swimming pool' },
  { norwegian: 'støvler', english: 'boots' },
  { norwegian: 'leie', english: 'rent' },
  { norwegian: 'regnjakken', english: 'rain coat' },
  { norwegian: 'lokale', english: 'local' },
  { norwegian: 'nærmeste', english: 'nearest' },
  { norwegian: 'dessertmenyen', english: 'the dessert menu' },
  { norwegian: 'denne stilen', english: 'this style' },
  { norwegian: 'uformell', english: 'informal' },
  { norwegian: 'forståelse', english: 'understanding' },
  { norwegian: 'foretrukne, foretrukket', english: 'preferred' },
  { norwegian: 'dessuten', english: 'furthermore' },
  { norwegian: 'takknemlig', english: 'grateful' },
  { norwegian: 'heldigvis', english: 'luckily' },
  { norwegian: 'virkeligheten', english: 'reality' },
  { norwegian: 'begeistret', english: 'excited' },
  { norwegian: 'nøyaktig', english: 'exact' },
  { norwegian: 'nøyaktighet', english: 'accuracy' },
  { norwegian: 'grunn,fordi', english: 'because' },
  { norwegian: 'skikkelig', english: 'properly' },
  { norwegian: 'merkelig', english: 'strange' },
  { norwegian: 'opplysningen', english: 'information' },
  { norwegian: 'uregelmessighet', english: 'irregularity' },
  { norwegian: 'antakelig', english: 'probably' },
  { norwegian: 'uansett', english: 'regardless' },
  { norwegian: 'høytidelig', english: 'solemnly' },
  { norwegian: 'overkommelig', english: 'manageable' },
  { norwegian: 'ydmykende', english: 'humiliating' },
  { norwegian: 'skade', english: 'damage' },
  { norwegian: 'bekymrer', english: 'worries' },
  { norwegian: 'allikevel', english: 'anyway' },
  { norwegian: 'temmelig', english: 'quite a bit' },
  { norwegian: 'foreløpig', english: 'for the time being' },
  { norwegian: 'i hvert fall', english: 'at least' },
  { norwegian: 'tåpelig', english: 'foolish' },
  { norwegian: 'forskjell', english: 'difference' },
  { norwegian: 'likegyldig', english: 'indifferent' },
  { norwegian: 'gidder', english: 'bother' },
  { norwegian: 'vesentlige', english: 'significant,essentials' },
  { norwegian: 'videre', english: 'further' },
  { norwegian: 'underliggende', english: 'underlying' },
  { norwegian: 'i stand til', english: 'capable of' },
  { norwegian: 'av og til', english: 'occasionally,sometimes' },
  { norwegian: 'sannhet', english: 'truth' },
  { norwegian: 'begeistring', english: 'excitement' },
  { norwegian: 'forvirrende', english: 'confusing' },
  { norwegian: 'uoppfordet', english: 'unsolicited' },
  { norwegian: 'tviler', english: 'doubt' },
  { norwegian: 'å forlange', english: 'to demand' },
  { norwegian: 'tilsynelatende', english: 'apparently' },
  { norwegian: 'å forsøk', english: 'to attempt' },
  { norwegian: 'til og med', english: 'even' },
  { norwegian: 'merkelig', english: 'strange' },
  { norwegian: 'tilfredsstillende', english: 'satisfactory' },
  { norwegian: 'å håndtere, å beherske', english: 'to handle' },
  { norwegian: 'å synes synd på', english: 'to feel sorry for' },
  { norwegian: 'fremdeles', english: 'still' },
  { norwegian: 'med det samme,med en gang', english: 'immediately,right away' },
  { norwegian: 'overrasket', english: 'surprised' },
  { norwegian: 'behandler', english: 'treats' },
  { norwegian: 'nemlig', english: 'in fact' },
  { norwegian: 'å innrømme nederlag', english: 'to admit defeat' },
  { norwegian: 'Til rådighet', english: 'At your disposal' },
  { norwegian: 'ufattelig', english: 'unbelievable' },
  { norwegian: 'evighet', english: 'eternity' },
  { norwegian: 'avstand', english: 'distance' },
  { norwegian: 'tiltrekker', english: 'attracts' },
  { norwegian: 'gjennomslag', english: 'impact' },
  { norwegian: 'på sikt', english: 'in the long run' },
  { norwegian: 'i den grad', english: 'to the extent' },
  { norwegian: 'vi kan godt', english: 'we know very well' },
  { norwegian: 'forandring', english: 'change' },
  { norwegian: 'en gang for alle', english: 'once and for all' },
  { norwegian: 'innbakt', english: 'baked in' },
  { norwegian: 'å skli', english: 'to slide' },
  { norwegian: 'hurtig', english: 'fast' },
  { norwegian: 'om å gjøre', english: 'all about' },
];
