import { Question } from './types';

export const data: Question[] = [
  { norwegian: 'tale', english: 'speech' },
  { norwegian: 'formidle', english: 'convey' },
  { norwegian: 'muntlig', english: 'oral' },
  { norwegian: 'arbeidslivsbalanse', english: 'work life balance' },
  { norwegian: 'å sørge for', english: 'to ensure' },
  { norwegian: 'forhandle', english: 'negotiate' },
  { norwegian: 'lønnsnivå', english: 'salary level' },
  { norwegian: 'arbeidsgiver', english: 'employer' },
  { norwegian: 'enighet', english: 'agreement' },
  { norwegian: 'sluttpakke', english: 'severance package' },
  { norwegian: 'å tilby', english: 'to offer' },
  { norwegian: 'frivillig', english: 'voluntary' },
  { norwegian: 'nedbemannet', english: 'downsized' },
  { norwegian: 'deltid', english: 'part time' },
  { norwegian: 'tilsyn', english: 'supervision' },
  { norwegian: 'faste arbeidstider', english: 'fixed working hours' },
  { norwegian: 'tilpasse start- og sluttidspunkt', english: 'adjust the start and end time' },
  { norwegian: 'frihet', english: 'freedom' },
  { norwegian: 'yrke', english: 'profession' },
  { norwegian: 'yrkesetikk', english: 'professional ethics' },
  { norwegian: 'faglige', english: 'professional' },
  { norwegian: 'bestemt,spesifikk', english: 'specific' },
  { norwegian: 'prinsipp', english: 'principle' },
  { norwegian: 'atferd,oppførsel', english: 'behavior' },
  { norwegian: 'fysiske', english: 'physical' },
  { norwegian: 'å forsinke', english: 'to delay' },
  { norwegian: 'å utsett', english: 'to postpone' },
  { norwegian: 'å delegere', english: 'to delegate' },
  { norwegian: 'medarbeidergjennomgang', english: 'employee review' },
  { norwegian: 'langsiktige', english: 'long-term' },
  { norwegian: 'tidsrammer', english: 'timeframes' },
  { norwegian: 'kjerne', english: 'core' },
  { norwegian: 'grunnleggende', english: 'basic' },
  { norwegian: 'unike', english: 'unique' },
  { norwegian: 'utstyr', english: 'equipment' },
  { norwegian: 'å opprette', english: 'to establish' },
  { norwegian: 'formell', english: 'formal' },
  { norwegian: 'å vedlikeholde', english: 'to maintain' },
  { norwegian: 'kunnskaper', english: 'knowledge' },
  { norwegian: 'karrierevekst', english: 'career growth' },
  { norwegian: 'tverrkulturelt', english: 'cross-culturally' },
  { norwegian: 'å samarbeide', english: 'to cooperate, collaborate' },
  { norwegian: 'bakgrunner', english: 'background' },
  { norwegian: 'å bestemme,å avgjøre', english: 'to decide' },
  { norwegian: 'konfliktløsning', english: 'conflict resolution' },
  { norwegian: 'uenigheter', english: 'disagreements' },
  { norwegian: 'erfaring', english: 'experience' },
  { norwegian: 'oppleve,erfaren', english: 'experienced' },
  { norwegian: 'veiledning', english: 'guidance' },
  { norwegian: 'støtte', english: 'support' },
  { norwegian: 'å overvåke', english: 'to supervise, to monitor' },
  { norwegian: 'kunnskapsoverføring', english: 'knowledge transfer' },
  { norwegian: 'ledelse', english: 'management' },
  { norwegian: 'å holde seg', english: 'to hold on' },
  { norwegian: 'fagfelt', english: 'professional field' },
  { norwegian: 'stil', english: 'style' },
  { norwegian: 'å foretrekke', english: 'to prefer' },
  { norwegian: 'tidsstyring', english: 'time management' },
  { norwegian: 'å maksimere', english: 'to maximize' },
  { norwegian: 'yrkesmessa', english: 'vocational fair' },
  { norwegian: 'å skifte', english: 'to replace' },
  { norwegian: 'å oppnå', english: 'to achieve' },
  { norwegian: 'tilnærming', english: 'approach' },
  { norwegian: 'aspekter', english: 'aspects' },
  { norwegian: 'endringer', english: 'changes' },
  { norwegian: 'målrettet', english: 'targeted' },
  { norwegian: 'kan oppnås', english: 'can be achieved' },
  { norwegian: 'ansvar', english: 'responsibility' },
  { norwegian: 'ansvarliggjøring', english: 'accountability' },
  { norwegian: 'ansvarlige', english: 'responsible' },
  { norwegian: 'handlinger og resultater', english: 'actions and results' },
  { norwegian: 'å overføre', english: 'to transfer' },
  { norwegian: 'inkluderende', english: 'inclusive' },
  { norwegian: 'mangfold', english: 'diversity' },
  { norwegian: 'verdsetter,verdier', english: 'values' },
  { norwegian: 'sosiale arrangementer', english: 'social events' },
  { norwegian: 'myndighet,autoritet', english: 'authority' },
  { norwegian: 'retningslinjer', english: 'guidelines' },
  { norwegian: 'beslutning', english: 'decision' },
  { norwegian: 'innenfor', english: 'within' },
  { norwegian: 'arbeidstakerdeltakelse', english: 'employee participation' },
  { norwegian: 'å delta', english: 'to attend, to participate' },
  { norwegian: 'rette', english: 'correct' },
  { norwegian: 'å fremme', english: 'promoting' },
  { norwegian: 'arbeidstakerdeltakelse', english: 'employee participation' },
  { norwegian: 'å oppmuntre til', english: 'to encourage' },
  { norwegian: 'oppmuntre', english: 'encourage' },
  { norwegian: 'oppmuntret', english: 'encouraged' },
  { norwegian: 'utelukkende', english: 'exclusively' },
  { norwegian: 'å lage', english: 'to create' },
  { norwegian: 'å understreke prestasjon, å vektlegge oppnåelse', english: 'to emphasize achievement' },
  { norwegian: 'forslag', english: 'suggestion' },
  { norwegian: 'uforanderlig arbeidstid', english: 'unchanging working hours' },
  { norwegian: 'å tilby', english: 'offering' },
  { norwegian: 'arbeidsordninger', english: 'work arrangements' },
  { norwegian: 'tilpasser seg', english: 'adapts' },
  { norwegian: 'behov', english: 'need' },
  { norwegian: 'å ivareta', english: 'to preserve' },
  { norwegian: 'å ta hensyn til,å overveie', english: 'to consider' },
  { norwegian: 'plasseringen', english: 'the location' },
  { norwegian: 'behandler', english: 'treats' },
  { norwegian: 'samhandler', english: 'interacts' },
  { norwegian: 'å utøve godt lederskap', english: 'to exercise good leadership' },
  { norwegian: 'felles', english: 'common' },
  { norwegian: 'veilede', english: 'guide' },
  { norwegian: 'veileder', english: 'supervisor' },
  { norwegian: 'emner', english: 'subjects' },
  { norwegian: 'utfordringer', english: 'challenges' },
  { norwegian: 'å fremme', english: 'to promote' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'ærlighet', english: 'honesty' },
  { norwegian: 'verdsatt', english: 'appreciated' },
  { norwegian: 'søke', english: 'seek' },
  { norwegian: 'skritt', english: 'steps' },
  { norwegian: 'selvstendig', english: 'independent' },
  { norwegian: 'selvstendige', english: 'independent' },
  { norwegian: 'utvide', english: 'expand' },
  { norwegian: 'i henhold til', english: 'according to' },
  { norwegian: 'å handle', english: 'to act, to shop' },
  { norwegian: 'handler', english: 'acts' },
  { norwegian: 'beslutninger', english: 'decisions' },
  { norwegian: 'utveksling', english: 'exchange' },
  { norwegian: 'å bidra', english: 'to contribute' },
  { norwegian: 'å håndtere', english: 'to handle, to manage' },
  { norwegian: 'frist', english: 'deadline' },
  { norwegian: 'tidsfrister', english: 'deadlines' },
  { norwegian: 'pålitelighet,pålitelig', english: 'reliable' },
  { norwegian: 'vesentlige', english: 'significant' },
  { norwegian: 'årsaker', english: 'causes' },
  { norwegian: 'passende', english: 'appropriate' },
  { norwegian: 'oppdaget', english: 'discovered' },
  { norwegian: 'å årsake', english: 'to cause' },
  { norwegian: 'å passe', english: 'to fit' },
  { norwegian: 'å oppdage', english: 'to discover' },
  { norwegian: 'å foreslå', english: 'to suggest' },
  { norwegian: 'å forbedre', english: 'to improve' },
  { norwegian: 'å uttrykke', english: 'to express' },
  { norwegian: 'å forlate', english: 'to leave' },
  { norwegian: 'å oppfordre', english: 'to urge' },
  { norwegian: 'å øke', english: 'to increase' },
  { norwegian: 'økt', english: 'increased' },
  { norwegian: 'utfordringer', english: 'challenges' },
  { norwegian: 'ansvar', english: 'responsibility' },
  { norwegian: 'ansvarlighet', english: 'responsibility' },
  { norwegian: 'ansvarlig', english: 'responsible' },
  { norwegian: 'hard', english: 'hard' },
  { norwegian: 'å fullføre', english: 'to complete' },
  { norwegian: 'utsatt', english: 'postponed' },
  { norwegian: 'forslag', english: 'proposal' },
  { norwegian: 'virdering', english: 'assessment' },
  { norwegian: 'vurdere', english: 'consider' },
  { norwegian: 'støtte', english: 'support' },
  { norwegian: 'utforske', english: 'explore' },
  { norwegian: 'ressursene', english: 'the resources' },
  { norwegian: 'ressurser', english: 'resources' },
  { norwegian: 'begrenset', english: 'limited' },
  { norwegian: 'å justere', english: 'to adjust' },
  { norwegian: 'behov', english: 'needs' },
  { norwegian: 'milepæl', english: 'milestone' },
  { norwegian: 'nådd', english: 'reached' },
  { norwegian: 'formidle', english: 'convey, communicate' },
  { norwegian: 'unngå', english: 'avoid' },
  { norwegian: 'nødvendig', english: 'necessary' },
  { norwegian: 'regelmessige', english: 'regular' },
  { norwegian: 'oppdrag', english: 'assignment' },
  { norwegian: 'klarhet', english: 'clarity' },
  { norwegian: 'ærlig', english: 'honesty' },
  { norwegian: 'å forberede seg', english: 'to prepare oneself' },
  { norwegian: 'vedlikehold', english: 'maintenance' },
  { norwegian: 'regelmessig', english: 'regularly' },
  { norwegian: 'egenskap', english: 'trait, quality' },
  { norwegian: 'vurdere', english: 'consider, assess' },
  { norwegian: 'fremgang', english: 'progress' },
  { norwegian: 'ferdigheter', english: 'skills' },
  { norwegian: 'ferdighetene', english: 'the skills' },
  { norwegian: 'avbryt', english: 'cancel' },
  { norwegian: 'forsette', english: 'continue' },
  { norwegian: 'skrivere', english: 'printers' },
  { norwegian: 'ved', english: 'by' },
  { norwegian: 'opplevelse', english: 'experience' },
  { norwegian: 'ytelse', english: 'performance' },
  { norwegian: 'fremfor', english: 'over' },
  { norwegian: 'utseende', english: 'look' },
  { norwegian: 'sammenheng', english: 'context' },
  { norwegian: 'tiltaleform', english: 'form of indictment' },
  { norwegian: 'overordnet', english: 'superior' },
  { norwegian: 'innebærer', english: 'implies' },
  { norwegian: 'overarbeid', english: 'overtime' },
  { norwegian: 'medarbeidersamtale', english: 'employee interview' },
  { norwegian: 'nettarbeid', english: 'computer work' },
  { norwegian: 'å utføre', english: 'to perform' },
  { norwegian: 'utføres', english: 'is performed, is carried out' },
  { norwegian: 'å forklare', english: 'to explain' },
  { norwegian: 'begrep', english: 'term' },
  { norwegian: 'å styrke', english: 'to strengthen' },
  { norwegian: 'forhold', english: 'relationship' },
  { norwegian: 'å overføre', english: 'to transfer' },
  { norwegian: 'lønnsøkning', english: 'salary increase' },
  { norwegian: 'stillingsbeskrivelse', english: 'job description' },
  { norwegian: 'ansvarsområder', english: 'areas of responsibility' },
  { norwegian: 'avdeling', english: 'department' },
  { norwegian: 'avdelinger', english: 'departments' },
  { norwegian: 'åpent kontorlandskap', english: 'open office landscape' },
  { norwegian: 'tariffavtale', english: 'collective agreement' },
  { norwegian: 'arbeidsforhold', english: 'working conditions' },
  { norwegian: 'forening', english: 'union,association' },
  { norwegian: 'verdier,verdsetter', english: 'values' },
  { norwegian: 'å styre', english: 'to control' },
  { norwegian: 'styrer', english: 'controls' },
  { norwegian: 'verdsatt', english: 'appreciated' },
  { norwegian: 'utføre', english: 'perform' },
  { norwegian: 'forvalte', english: 'manage,maintain' },
  { norwegian: 'tidsforvaltning', english: 'time management' },
  { norwegian: 'forutseende', english: 'anticipatory' },
  { norwegian: 'establish', english: 'etablere' },
  { norwegian: 'anerkjennelse', english: 'recognition' },
  { norwegian: 'knyttet', english: 'attached' },
  { norwegian: 'arbeidsytelse', english: 'work performance' },
  { norwegian: 'medarbeider,ansatte', english: 'employee,co-worker' },
  { norwegian: 'undersøkelse', english: 'exam,survey' },
  { norwegian: 'medarbeiderundersøkelse', english: 'employee survey' },
  { norwegian: 'kunde', english: 'customer' },
  { norwegian: 'tilfredshet', english: 'satisfaction' },
  { norwegian: 'kundetilfredshet', english: 'customer satisfaction' },
  { norwegian: 'innsats', english: 'efforts' },
  { norwegian: 'stramt', english: 'tight' },
  { norwegian: 'frist', english: 'deadline' },
  { norwegian: 'krav', english: 'requirement,demand' },
  { norwegian: 'krav', english: 'requirements,demands' },
  { norwegian: 'kravet', english: 'the requirement' },
  { norwegian: 'kravene', english: 'the requirements' },
  { norwegian: 'likestilling', english: 'equality' },
  { norwegian: 'har like', english: 'have equal' },
  { norwegian: 'rettferdig', english: 'fairly' },
  { norwegian: 'kjønn, alder, etnisitet osv.', english: 'gender, age, ethnicity, etc.' },
  { norwegian: 'evne', english: 'skill' },
  { norwegian: 'evnen', english: 'the ability' },
  { norwegian: 'tykkere', english: 'thicker' },
  { norwegian: 'vaskemidler', english: 'detergents' },
  { norwegian: 'vifte', english: 'fan' },
  { norwegian: 'gardiner', english: 'curtains' },
  { norwegian: 'la kranen renne', english: 'let the faucet run' },
  { norwegian: 'oppvaskmaskin', english: 'dishwasher' },
  { norwegian: 'hastighet,fart', english: 'speed' },
  { norwegian: 'søppelkasse', english: 'trash can' },
  { norwegian: 'estetikk', english: 'aesthetics' },
  { norwegian: 'trivsel', english: 'well being' },
  { norwegian: 'uorganiserte', english: 'disorganized' },
  { norwegian: 'overfylte med ting', english: 'cluttered' },
  { norwegian: 'å skape', english: 'to create' },
  { norwegian: 'innbydende atmosfære', english: 'welcoming atmosphere' },
  { norwegian: 'lukkede', english: 'closed' },
  { norwegian: 'hyppig,hyppige', english: 'frequent' },
  { norwegian: 'arter', english: 'species' },
  { norwegian: 'å kreve', english: 'to demand, require' },
  { norwegian: 'laveste', english: 'lowest' },
  { norwegian: 'fylt', english: 'filled' },
  { norwegian: 'fult', english: 'full' },
  { norwegian: 'overflater', english: 'surfaces' },
  { norwegian: 'synlig', english: 'visible' },
  { norwegian: 'skitt', english: 'dirt' },
  { norwegian: 'kjøkkenutstyr', english: 'kitchen utensils' },
  { norwegian: 'å desinfisere', english: 'to disinfect' },
  { norwegian: 'i tillegg til', english: 'in addition to' },
  { norwegian: 'komfortabelt', english: 'comfortable' },
  { norwegian: 'avslappende', english: 'relaxing' },
  { norwegian: 'slå', english: 'turn' },
  { norwegian: 'slå av', english: 'turn off' },
  { norwegian: 'slå på', english: 'turn on' },
  { norwegian: 'slått på, skrudd på', english: 'turned on' },
  { norwegian: 'beroligende', english: 'calming, soothing' },
  { norwegian: 'å oppbevare', english: 'to store, keep' },
  { norwegian: 'utstyr', english: 'equipment' },
  { norwegian: 'hjern', english: 'brain' },
  { norwegian: 'hjernen', english: 'the brain' },
  { norwegian: 'luftkvaliteten', english: 'the air quality' },
  { norwegian: 'luftfuktere', english: 'humidifiers' },
  { norwegian: 'å tilføre,å legge til', english: 'to add' },
  { norwegian: 'inneluft', english: 'indoor air' },
  { norwegian: 'levetiden', english: 'the life time' },
  { norwegian: 'å overbelaste', english: 'to overload' },
  { norwegian: 'produsenten', english: 'the manufacturer' },
  { norwegian: 'blant', english: 'among' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'å innføre,introdusere', english: 'to introduce' },
  { norwegian: 'strømregninger', english: 'electricity bills' },
  { norwegian: 'strømsparemodus', english: 'power saving mode' },
  { norwegian: 'vannbesparende', english: 'water saving' },
  { norwegian: 'dusjhode', english: 'shower head' },
  { norwegian: 'programmerbare', english: 'programmable' },
  { norwegian: 'termostater', english: 'thermostats' },
  { norwegian: 'kilder', english: 'sources' },
  { norwegian: 'mur,vegg', english: 'wall' },
  { norwegian: 'lydisolerende', english: 'soundproofing' },
  { norwegian: 'vant til', english: 'used to' },
  { norwegian: 'å bevare', english: 'to preserve' },
  { norwegian: 'stille', english: 'quiet' },
  { norwegian: 'å stille inn', english: 'to set in' },
  { norwegian: 'matvarer', english: 'foodstuffs, food' },
  { norwegian: 'å vaske klær', english: 'to do laundry' },
  { norwegian: 'stoff', english: 'fabric' },
  { norwegian: 'avstengningsventil', english: 'shut-off valve' },
  { norwegian: 'bøtte', english: 'bucket' },
  { norwegian: 'svamp', english: 'sponge' },
  { norwegian: 'etterfulgt av', english: 'followed by' },
  { norwegian: 'skylling', english: 'rinse' },
  {
    norwegian: 'hjemmeunderholdningssystem',
    english: 'home entertainment system',
  },
  { norwegian: 'tilgang', english: 'access' },
  { norwegian: 'å beholde, å holde', english: 'to retain, to keep' },
  { norwegian: 'fuktigheten', english: 'the humidity' },
  { norwegian: 'fuktighet', english: 'moisture' },
  { norwegian: 'kjølig', english: 'cool' },
  { norwegian: 'luftforurensning', english: 'air pollution' },
  { norwegian: 'rengjøringsprodukter', english: 'cleaning products' },
  { norwegian: 'å lufte ut', english: 'to air out,ventilate' },
  { norwegian: 'å forlenge', english: 'to extend,prolong' },
  { norwegian: 'slitasje', english: 'wear and tear' },
  { norwegian: 'påslått', english: 'switched on' },
  { norwegian: 'påslåing', english: 'switching on' },
  { norwegian: 'støvfrie', english: 'dust free' },
  { norwegian: 'overoppheting', english: 'overheating' },
  { norwegian: 'fuktige', english: 'moist' },
  { norwegian: 'lader kontinuerlig', english: 'charging continuously' },
  { norwegian: 'å fremskynde', english: 'to speed up' },
  { norwegian: 'kraftig', english: 'powerful' },
  { norwegian: 'stråle', english: 'beam' },
  { norwegian: 'matrester', english: 'leftover food' },
  { norwegian: 'kjeller', english: 'basement' },
  { norwegian: 'mugg', english: 'mold' },
  { norwegian: 'avfukter', english: 'dehumidifier' },
  { norwegian: 'nødvendig', english: 'necessary' },
  { norwegian: 'oppvask', english: 'dishes' },
  { norwegian: 'oppvasken', english: 'the dishes' },
  { norwegian: 'cycles', english: 'sykluser' },
  { norwegian: 'nivå', english: 'level' },
  { norwegian: 'lydnivået', english: 'the sound level' },
  { norwegian: 'å motvirke', english: 'to counteract' },
  { norwegian: 'gulvflater', english: 'floor surfaces' },
  { norwegian: 'teppe', english: 'carpet' },
  { norwegian: 'myke', english: 'soft' },
  { norwegian: 'møbler', english: 'furniture' },
  { norwegian: 'lokk', english: 'lid' },
  { norwegian: 'gryte og pann', english: 'pot and pan' },
  { norwegian: 'vannbesparelse', english: 'water saving' },
  { norwegian: 'lavt-flyt', english: 'low flow' },
  { norwegian: 'engasjerende', english: 'engaging' },
  { norwegian: 'vaskeliste', english: 'laundry list' },
  { norwegian: 'belønninger', english: 'rewards' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'a utføre', english: 'to carry out' },
  { norwegian: 'utfører', english: 'performs' },
  { norwegian: 'ulike', english: 'different' },
  { norwegian: 'husarbeidsoppgaver', english: 'housework tasks' },
  { norwegian: 'tidskrevende', english: 'time consuming' },
  { norwegian: 'bærekraftige', english: 'sustainable' },
  { norwegian: 'oppsett', english: 'setup' },
  { norwegian: 'samtidig', english: 'simultaneous' },
  { norwegian: 'økt', english: 'increased' },
  { norwegian: 'å håndtere', english: 'to manage, to handle' },
  { norwegian: 'enheter', english: 'devices,units' },
  { norwegian: 'enheten', english: 'the device,the unit' },
  { norwegian: 'enhetene', english: 'the devices, the units' },
  { norwegian: 'påslått', english: 'switched on' },
  { norwegian: 'matbutikken', english: 'the grocery store' },
  { norwegian: 'engangsplastposer', english: 'disposable plastic bags' },
  { norwegian: 'forventer', english: 'expects' },
  { norwegian: 'samle opp', english: 'pick up' },
  { norwegian: 'rot', english: 'mess' },
  { norwegian: 'rengjøre og rydde', english: 'clean and clear' },
  { norwegian: 'på forhånd', english: 'in advance' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'begrense', english: 'restrict, limit' },
  { norwegian: 'skape', english: 'create' },
  { norwegian: 'skade', english: 'damage' },
  { norwegian: 'ødelagt', english: 'destroyed' },
  { norwegian: 'ærlig', english: 'honest' },
  { norwegian: 'ærlighet', english: 'honesty' },
  { norwegian: 'sikkerhet', english: 'safety' },
  { norwegian: 'trygt', english: 'safe' },
  { norwegian: 'ta vare på deg selv', english: 'take care of yourself' },
  { norwegian: 'vær forsiktig', english: 'be careful' },
  { norwegian: 'ulåste', english: 'unlocked' },
  { norwegian: 'låst', english: 'locked' },
  { norwegian: 'røykvarsler', english: 'smoke alarm' },
  { norwegian: 'sikkerhetssystem', english: 'security system' },
  { norwegian: 'sjelden', english: 'rarely' },
  { norwegian: 'framtid,fremtid', english: 'future' },
  { norwegian: 'framover,fremover', english: 'forwards' },
  { norwegian: 'på forhånd', english: 'in advance' },
  { norwegian: 'alder', english: 'age' },
  { norwegian: 'ovner', english: 'furnace, heater, ovens' },
  { norwegian: 'isolere', english: 'isolate, insulate' },
  { norwegian: 'beslutningen', english: 'the decision' },
  { norwegian: 'til slutt', english: 'in the end' },
  { norwegian: 'inngrep', english: 'interventions' },
  { norwegian: 'lagring', english: 'storage' },
  { norwegian: 'komplisert', english: 'complicated' },
  { norwegian: 'resirkulering', english: 'recycling' },
  { norwegian: 'resirkulere', english: 'recycle' },
  { norwegian: 'erstatte', english: 'replace' },
  { norwegian: 'gjenbrukbare', english: 'reusable' },
  { norwegian: 'å oppmuntre', english: 'to encourage' },
  { norwegian: 'sunn,sunt', english: 'healthy' },
  { norwegian: 'matlaging', english: 'cooking' },
  { norwegian: 'ferske', english: 'fresh' },
  { norwegian: 'ferdigmat', english: 'ready meals' },
  { norwegian: 'uavhengig', english: 'regardless,independent' },
  { norwegian: 'lesing', english: 'reading' },
  { norwegian: 'tilgjengelig', english: 'available' },
  { norwegian: 'rekke', english: 'variety' },
  { norwegian: 'felles', english: 'common' },
  { norwegian: 'rot', english: 'clutter' },
  { norwegian: 'å forvalte', english: 'to manage' },
  { norwegian: 'utgifter', english: 'expenses' },
  { norwegian: 'inntekter', english: 'income' },
  { norwegian: 'følge', english: 'follow' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'luksus', english: 'luxury' },
  { norwegian: 'varer', english: 'items, goods' },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'livsstil', english: 'lifestyle' },
  { norwegian: 'gjenbruke', english: 'reuse' },
  { norwegian: 'modus', english: 'mode' },
  { norwegian: 'husholdningen', english: 'the household' },
  { norwegian: 'barnegrinder', english: 'childsgate' },
  { norwegian: 'sikkerhetsutstyr', english: 'safety devices' },
  { norwegian: 'rengjøringsmidler', english: 'cleaning agents' },
  { norwegian: 'gjenstander', english: 'objects' },
  { norwegian: 'husholdningsartikler', english: 'household items' },
  { norwegian: 'erstattes', english: 'is replaced' },
  { norwegian: 'å fremme', english: 'to promote' },
  { norwegian: 'regelmessig', english: 'regularly' },
  { norwegian: 'kosthold', english: 'diet' },
  { norwegian: 'mengder', english: 'amounts, quantities' },
  { norwegian: 'umiddelbart', english: 'immediately' },
  { norwegian: 'fryser', english: 'freezer' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'luftrenser', english: 'air cleaner' },
  { norwegian: 'ferdigheter', english: 'skills' },
  { norwegian: 'reparasjoner', english: 'repairs' },
  { norwegian: 'ryddigere', english: 'tidier' },
  { norwegian: 'badet', english: 'the bathroom' },
  { norwegian: 'bad', english: 'bathroom' },
  { norwegian: 'grundig', english: 'thoroughly' },
  { norwegian: 'å samle', english: 'to collect,to gather' },
  { norwegian: 'ubrukt', english: 'unused' },
  { norwegian: 'støy,bråk', english: 'noise' },
  { norwegian: 'å dekke', english: 'to cover' },
  { norwegian: 'lyder', english: 'sounds' },
  { norwegian: 'tykk', english: 'thick' },
  { norwegian: 'handler klær', english: 'shopping for clothes' },
  { norwegian: 'å vurdere', english: 'to consider' },
  { norwegian: 'å sikre', english: 'to secure' },
  { norwegian: 'noe som passer godt', english: 'something that fits well' },
  { norwegian: 'størrelse', english: 'size' },
  { norwegian: 'god passform', english: 'good fit' },
  { norwegian: 'utelukkende', english: 'exclusively' },
  { norwegian: 'merke', english: 'mark' },
  { norwegian: 'trender', english: 'trends' },
  { norwegian: 'størrelsesetiketter', english: 'size labels' },
  { norwegian: 'dyreste', english: 'most expensive' },
  { norwegian: 'uavhengig', english: 'regardless' },
  { norwegian: 'handlevogn', english: 'shopping cart' },
  { norwegian: 'gjenstander', english: 'objects' },
  { norwegian: 'et vare', english: 'an item' },
  { norwegian: 'fasthet', english: 'firmness' },
  { norwegian: 'skadet', english: 'hurt' },
  { norwegian: 'moden', english: 'ripe,mature' },
  { norwegian: 'overmoden', english: 'overripe' },
  { norwegian: 'bestill', english: 'order' },
  { norwegian: 'forrett', english: 'appetizer' },
  { norwegian: 'hovedrett', english: 'main course' },
  { norwegian: 'matopplevelse', english: 'dining experience' },
  { norwegian: 'en rett', english: 'a dish' },
  { norwegian: 'gjett', english: 'guess' },
  { norwegian: 'vanligvis', english: 'usually' },
  { norwegian: 'fysiske', english: 'physical' },
  { norwegian: 'plagg', english: 'garment' },
  { norwegian: 'å sammenligne', english: 'to compare' },
  { norwegian: 'kvalitetsråvarer', english: 'quality raw materials' },
  { norwegian: 'utløpsdatoer', english: 'expiration dates' },
  { norwegian: 'friskhet', english: 'freshness' },
  { norwegian: 'utseende', english: 'appearance' },
  { norwegian: 'hermetiserte', english: 'canned' },
  { norwegian: 'varer', english: 'goods' },
  { norwegian: 'hylle', english: 'shelf' },
  { norwegian: 'matforgiftning', english: 'food poisoning' },
  { norwegian: 'å tilberede et måltid', english: 'to prepare a meal' },
  { norwegian: 'a forberede', english: 'to prepare' },
  { norwegian: 'skjærebrett', english: 'cutting board' },
  { norwegian: 'kjøkkenutstyr', english: 'kitchen utensils' },
  { norwegian: 'moten', english: 'the fashion' },
  { norwegian: 'tidkrevende', english: 'time consuming' },
  { norwegian: 'oppskrifter', english: 'recipes' },
  { norwegian: 'ferskhet', english: 'freshness' },
  { norwegian: 'tegn', english: 'signs' },
  { norwegian: 'kanter', english: 'edges' },
  { norwegian: 'risikoen', english: 'the risk' },
  { norwegian: 'ved berøring', english: 'by touch' },
  { norwegian: 'matvarer', english: 'foodstuffs' },
  { norwegian: 'matsvinn', english: 'food waste' },
  { norwegian: 'mengder', english: 'amounts' },
  { norwegian: 'kvantumsrabatt', english: 'quantity discount' },
  { norwegian: 'uavhengig', english: 'independent' },
  { norwegian: 'holdbarheten', english: 'durability,shelf life' },
  { norwegian: 'opprettholde', english: 'maintain' },
  { norwegian: 'oppbevaringskrav', english: 'storage requirements' },
  { norwegian: 'øverste hyllene', english: 'top shelves' },
  { norwegian: 'anmeldelser', english: 'reviews' },
  { norwegian: 'kundeanmeldelser', english: 'customer reviews' },
  { norwegian: 'anbefalinger', english: 'recommendations' },
  { norwegian: 'kun', english: 'only' },
  { norwegian: 'kjedesteder', english: 'chain locations' },
  { norwegian: 'tilnærming', english: 'approach' },
  { norwegian: 'sunne', english: 'healthy' },
  { norwegian: 'alternativer', english: 'options' },
  { norwegian: 'næringsinformasjonen', english: 'the nutritional information' },
  { norwegian: 'uansett', english: 'regardless' },
  { norwegian: 'sjanser', english: 'chances' },
  { norwegian: 'varige', english: 'lasting' },
  { norwegian: 'investeringer', english: 'investments' },
  { norwegian: 'luksusmerker', english: 'luxury brands' },
  {
    norwegian: 'meld deg på nyhetsbrev',
    english: 'sign up for the newsletter',
  },
  { norwegian: 'ved å være', english: 'by being' },
  { norwegian: 'billig', english: 'cheap' },
  { norwegian: 'mengde', english: 'quantity' },
  { norwegian: 'plastavfall', english: 'plastic waste' },
  { norwegian: 'dagligvarer', english: 'groceries' },
  { norwegian: 'hermetikk', english: 'canned' },
  { norwegian: 'unødvendig', english: 'unnecessary' },
  { norwegian: 'plastemballasjer', english: 'plastic packaging' },
  { norwegian: 'fordel', english: 'advantage, benefit' },
  { norwegian: 'fordeler', english: 'benefits, advantages' },
  { norwegian: 'fordelene', english: 'the benefits' },
  { norwegian: 'bevaring', english: 'conservation, preservation, retention' },
  { norwegian: 'holdbarhet', english: 'shelf life' },
  { norwegian: 'inneholder', english: 'contains' },
  { norwegian: 'konserveringsmidler', english: 'preservatives' },
  { norwegian: 'ulike', english: 'different' },
  { norwegian: 'utgitt', english: 'released' },
  {
    norwegian: 'utseende og popularitet',
    english: 'appearance and popularity',
  },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'kunstige', english: 'artificial' },
  { norwegian: 'motetrender', english: 'fashion trends' },
  { norwegian: 'kleskjeder', english: 'clothing chains' },
  { norwegian: 'når det gjelder', english: 'when it comes to' },
  { norwegian: 'impulskjøp', english: 'impulse buy' },
  { norwegian: 'kvantumsrabatter', english: 'quantity discounts' },
  { norwegian: 'hurtigmat', english: 'fast food' },
  { norwegian: 'innhold', english: 'content' },
  { norwegian: 'næringsinnhold', english: 'nutritional content' },
  { norwegian: 'lavt fett', english: 'low fat' },
  { norwegian: 'rimelig', english: 'reasonable,affordable' },
  { norwegian: 'skinnende', english: 'shiny' },
  { norwegian: 'gjeller', english: 'gills' },
  { norwegian: 'skinn', english: 'leather' },
  { norwegian: 'stoff', english: 'fabric' },
  { norwegian: 'skall', english: 'shell' },
  { norwegian: 'utsikt', english: 'view' },
  { norwegian: 'utmerket', english: 'excellent' },
  { norwegian: 'vennligst', english: 'please' },
  { norwegian: 'vanntette,vanntett materiale', english: 'waterproof' },
  { norwegian: 'ull', english: 'wool' },
  { norwegian: 'fullkornsbrød', english: 'whole grain bread' },
  { norwegian: 'glutenfritt', english: 'gluten free' },
  { norwegian: 'kart', english: 'map' },
  { norwegian: 'meieri', english: 'dairy' },
  { norwegian: 'koffeinfri', english: 'decaffeinated' },
  { norwegian: 'innkvartere', english: 'accommodate' },
  { norwegian: 'importert', english: 'imported' },
  { norwegian: 'fettfattige', english: 'low fat' },
  { norwegian: 'geitemelk', english: "goat's milk" },
  { norwegian: 'guidede', english: 'guided' },
  { norwegian: 'skjerf', english: 'scarf' },
  { norwegian: 'opphold', english: 'stay' },
  { norwegian: 'forlenge', english: 'extend' },
  { norwegian: 'krydret', english: 'spiced' },
  { norwegian: 'stark', english: 'spicy' },
  { norwegian: 'kasjmir', english: 'cashmere' },
  { norwegian: 'skivet', english: 'sliced' },
  { norwegian: 'kjole', english: 'dress' },
  { norwegian: 'flytende', english: 'fluid' },
  { norwegian: 'økologisk', english: 'ecological,organic' },
  { norwegian: 'svømmebassenget', english: 'the swimming pool' },
  { norwegian: 'støvler', english: 'boots' },
  { norwegian: 'leie', english: 'rent' },
  { norwegian: 'regnjakken', english: 'rain coat' },
  { norwegian: 'lokale', english: 'local' },
  { norwegian: 'nærmeste', english: 'nearest' },
  { norwegian: 'dessertmenyen', english: 'the dessert menu' },
  { norwegian: 'denne stilen', english: 'this style' },
  { norwegian: 'uformell', english: 'informal' },
  { norwegian: 'forståelse', english: 'understanding' },
  { norwegian: 'foretrukne, foretrukket', english: 'preferred' },
  { norwegian: 'dessuten', english: 'furthermore' },
  { norwegian: 'takknemlig', english: 'grateful' },
  { norwegian: 'heldigvis', english: 'luckily' },
  { norwegian: 'virkeligheten', english: 'reality' },
  { norwegian: 'begeistret', english: 'excited' },
  { norwegian: 'nøyaktig', english: 'exact' },
  { norwegian: 'nøyaktighet', english: 'accuracy' },
  { norwegian: 'grunn,fordi', english: 'because' },
  { norwegian: 'skikkelig', english: 'properly' },
  { norwegian: 'merkelig', english: 'strange' },
  { norwegian: 'opplysningen', english: 'information' },
  { norwegian: 'uregelmessighet', english: 'irregularity' },
  { norwegian: 'antakelig', english: 'probably' },
  { norwegian: 'uansett', english: 'regardless' },
  { norwegian: 'høytidelig', english: 'solemnly' },
  { norwegian: 'overkommelig', english: 'manageable' },
  { norwegian: 'ydmykende', english: 'humiliating' },
  { norwegian: 'skade', english: 'damage' },
  { norwegian: 'bekymrer', english: 'worries' },
  { norwegian: 'allikevel', english: 'anyway' },
  { norwegian: 'temmelig', english: 'quite a bit' },
  { norwegian: 'foreløpig', english: 'for the time being' },
  { norwegian: 'i hvert fall', english: 'at least' },
  { norwegian: 'tåpelig', english: 'foolish' },
  { norwegian: 'forskjell', english: 'difference' },
  { norwegian: 'likegyldig', english: 'indifferent' },
  { norwegian: 'gidder', english: 'bother' },
  { norwegian: 'vesentlige', english: 'significant,essentials' },
  { norwegian: 'videre', english: 'further' },
  { norwegian: 'underliggende', english: 'underlying' },
  { norwegian: 'i stand til', english: 'capable of' },
  { norwegian: 'av og til', english: 'occasionally,sometimes' },
  { norwegian: 'sannhet', english: 'truth' },
  { norwegian: 'begeistring', english: 'excitement' },
  { norwegian: 'forvirrende', english: 'confusing' },
  { norwegian: 'uoppfordet', english: 'unsolicited' },
  { norwegian: 'tviler', english: 'doubt' },
  { norwegian: 'å forlange', english: 'to demand' },
  { norwegian: 'tilsynelatende', english: 'apparently' },
  { norwegian: 'å forsøk', english: 'to attempt' },
  { norwegian: 'til og med', english: 'even' },
  { norwegian: 'merkelig', english: 'strange' },
  { norwegian: 'tilfredsstillende', english: 'satisfactory' },
  { norwegian: 'å håndtere, å beherske', english: 'to handle' },
  { norwegian: 'å synes synd på', english: 'to feel sorry for' },
  { norwegian: 'fremdeles', english: 'still' },
  { norwegian: 'med det samme,med en gang', english: 'immediately,right away' },
  { norwegian: 'overrasket', english: 'surprised' },
  { norwegian: 'behandler', english: 'treats' },
  { norwegian: 'nemlig', english: 'in fact' },
  { norwegian: 'å innrømme nederlag', english: 'to admit defeat' },
  { norwegian: 'Til rådighet', english: 'At your disposal' },
  { norwegian: 'ufattelig', english: 'unbelievable' },
  { norwegian: 'evighet', english: 'eternity' },
  { norwegian: 'avstand', english: 'distance' },
  { norwegian: 'tiltrekker', english: 'attracts' },
  { norwegian: 'gjennomslag', english: 'impact' },
  { norwegian: 'på sikt', english: 'in the long run' },
  { norwegian: 'i den grad', english: 'to the extent' },
  { norwegian: 'vi kan godt', english: 'we know very well' },
  { norwegian: 'forandring', english: 'change' },
  { norwegian: 'en gang for alle', english: 'once and for all' },
  { norwegian: 'innbakt', english: 'baked in' },
  { norwegian: 'å skli', english: 'to slide' },
  { norwegian: 'hurtig', english: 'fast' },
  { norwegian: 'om å gjøre', english: 'all about' },
  { norwegian: 'Hei', english: 'Hello' },
  { norwegian: 'Takk', english: 'Thank you' },
  { norwegian: 'Vær så snill', english: 'Please' },
  { norwegian: 'Unnskyld', english: 'Excuse me' },
  { norwegian: 'Jeg forstår ikke', english: 'I do not understand' },
  { norwegian: 'Snakker du engelsk?', english: 'Do you speak English?' },
  { norwegian: 'Hva heter du?', english: 'What is your name?' },
  { norwegian: 'Jeg heter...', english: 'My name is...' },
  { norwegian: 'Hvordan har du det?', english: 'How are you?' },
  { norwegian: 'Jeg har det bra, takk', english: 'I am fine, thank you' },
  { norwegian: 'Hva er klokken?', english: 'What time is it?' },
  { norwegian: 'Unnskyld, hvor er toalettet?', english: 'Excuse me, where is the toilet?' },
  { norwegian: 'Jeg trenger hjelp', english: 'I need help' },
  { norwegian: 'Hvor mye koster dette?', english: 'How much does this cost?' },
  { norwegian: 'Kan jeg betale med kort?', english: 'Can I pay with a card?' },
  { norwegian: 'Jeg vil gjerne ha...', english: 'I would like...' },
  { norwegian: 'Kan du hjelpe meg?', english: 'Can you help me?' },
  { norwegian: 'Selvfølgelig', english: 'Of course' },
  { norwegian: 'Ingen årsak', english: 'You are welcome' },
  { norwegian: 'Jeg elsker deg', english: 'I love you' },
  { norwegian: 'Jeg savner deg', english: 'I miss you' },
  { norwegian: 'Hva tenker du om...?', english: 'What do you think about...?' },
  { norwegian: 'Jeg er sulten', english: 'I am hungry' },
  { norwegian: 'Jeg er tørst', english: 'I am thirsty' },
  { norwegian: 'Er det mulig?', english: 'Is it possible?' },
  { norwegian: 'Selvsagt', english: 'Certainly' },
  { norwegian: 'Jeg er enig', english: 'I agree' },
  { norwegian: 'Jeg er uenig', english: 'I disagree' },
  { norwegian: 'Jeg vet ikke', english: 'I do not know' },
  { norwegian: 'Kan du snakke saktere?', english: 'Can you speak slower?' },
  { norwegian: 'Kan du gjenta det?', english: 'Can you repeat that?' },
  { norwegian: 'Hvor kommer du fra?', english: 'Where are you from?' },
  { norwegian: 'Jeg kommer fra...', english: 'I come from...' },
  { norwegian: 'Hva liker du å gjøre?', english: 'What do you like to do?' },
  { norwegian: 'Jeg liker å...', english: 'I like to...' },
  { norwegian: 'Hvordan sier man... på norsk?', english: 'How do you say... in Norwegian?' },
  { norwegian: 'Hva betyr...?', english: 'What does... mean?' },
  { norwegian: 'Kan vi møtes igjen?', english: 'Can we meet again?' },
  { norwegian: 'Jeg ser frem til vårt neste møte', english: 'I look forward to our next meeting' },
  { norwegian: 'Ta vare på deg selv', english: 'Take care of yourself' },
  { norwegian: 'God natt', english: 'Good night' },
  { norwegian: 'Jeg er lei meg', english: 'I am sorry' },
  { norwegian: 'Gratulerer', english: 'Congratulations' },
  { norwegian: 'God tur', english: 'Have a nice trip' },
  { norwegian: 'Jeg føler meg syk', english: 'I feel sick' },
  { norwegian: 'Jeg har det gøy', english: 'I am having fun' },
  { norwegian: 'Jeg er kjedet', english: 'I am bored' },
  { norwegian: 'Jeg er trøtt', english: 'I am tired' },
  { norwegian: 'Jeg er spent', english: 'I am excited' },
  { norwegian: 'Jeg er nervøs', english: 'I am nervous' },
  { norwegian: 'Jeg er fullstendig enig', english: 'I completely agree' },
  { norwegian: 'Det spørs', english: 'It depends' },
  { norwegian: 'Ikke vær dum', english: 'do not be silly' },
  { norwegian: 'Det høres bra ut', english: 'That sounds good' },
  { norwegian: 'La oss gjøre det', english: 'let us do it' },
  { norwegian: 'Hold kontakten', english: 'Stay in touch' },
  { norwegian: 'Det var hyggelig å treffe deg', english: 'It was nice to meet you' },
  { norwegian: 'Hva skjer?', english: 'what is happening?' },
  { norwegian: 'Pass på deg selv', english: 'Look after yourself' },
  { norwegian: 'Jeg ble overrasket', english: 'I was surprised' },
  { norwegian: 'Det er verdt et forsøk', english: 'it is worth a try' },
  { norwegian: 'Jeg er ferdig', english: 'I am done' },
  { norwegian: 'Kan du anbefale en god restaurant?', english: 'Can you recommend a good restaurant?' },
  { norwegian: 'Hvor lang tid tar det?', english: 'How long does it take?' },
  { norwegian: 'Kan du skrive det ned?', english: 'Can you write it down?' },
  { norwegian: 'Jeg er allergisk mot...', english: 'I am allergic to...' },
  { norwegian: 'Jeg er imponert', english: 'I am impressed' },
  { norwegian: 'Det gjør ingenting', english: 'It does not matter' },
  { norwegian: 'Jeg er forsinket', english: 'I am late' },
  { norwegian: 'Kan du forklare det?', english: 'Can you explain it?' },
  { norwegian: 'Det er for dyrt', english: 'it is too expensive' },
  { norwegian: 'Kan du vise meg veien?', english: 'Can you show me the way?' },
  { norwegian: 'Jeg har gått meg vill', english: 'I am lost' },
  { norwegian: 'Kan jeg få kvitteringen, vær så snill?', english: 'Can I have the receipt, please?' },
  { norwegian: 'Jeg er interessert i...', english: 'I am interested in...' },
  { norwegian: 'Det kunne vært verre', english: 'It could be worse' },
  { norwegian: 'Hva foreslår du?', english: 'What do you suggest?' },
  { norwegian: 'Jeg er bekymret for...', english: 'I am worried about...' },
  { norwegian: 'Det er på tide å gå', english: 'it is time to go' },
  { norwegian: 'Kan jeg hjelpe deg med noe?', english: 'Can I help you with anything?' },
  { norwegian: 'Hva er meningen med livet?', english: 'What is the meaning of life?' },
  { norwegian: 'Det gir ingen mening', english: 'It makes no sense' },
  { norwegian: 'Jeg er stolt av deg', english: 'I am proud of you' },
  { norwegian: 'Det var en gang', english: 'Once upon a time' },
  { norwegian: 'Livet er vakkert', english: 'Life is beautiful' },
  { norwegian: 'Jeg er avhengig av...', english: 'I am addicted to...' },
  { norwegian: 'Det er ikke verdt det', english: 'it is not worth it' },
  { norwegian: 'Jeg føler meg hjemme', english: 'I feel at home' },
  { norwegian: 'Jeg har bestemt meg for...', english: 'I have decided to...' },
  { norwegian: 'Det endte godt', english: 'It ended well' },
  { norwegian: 'La oss holde kontakten', english: 'let us keep in touch' },
  { norwegian: 'Kan du låne meg...?', english: 'Can you lend me...?' },
  { norwegian: 'Jeg beundrer deg', english: 'I admire you' },
  { norwegian: 'Jeg er takknemlig for...', english: 'I am grateful for...' },
  { norwegian: 'Det er utenfor min kontroll', english: 'it is out of my control' },
  { norwegian: 'Hva er din drøm?', english: 'What is your dream?' },
  { norwegian: 'Det føles riktig', english: 'It feels right' },
  { norwegian: 'La oss endre emnet', english: 'let us change the subject' },
  { norwegian: 'Jeg har respekt for deg', english: 'I respect you' },
  { norwegian: 'Det overgår mine forventninger', english: 'It exceeds my expectations' },
  { norwegian: 'påvirkning', english: 'influence' },
  { norwegian: 'antagelse', english: 'assumption' },
  { norwegian: 'kompleksitet', english: 'complexity' },
  { norwegian: 'diskurs', english: 'discourse' },
  { norwegian: 'implikasjon', english: 'implication' },
  { norwegian: 'nyansert', english: 'nuanced' },
  { norwegian: 'paradigme', english: 'paradigm' },
  { norwegian: 'retorikk', english: 'rhetoric' },
  { norwegian: 'spektrum', english: 'spectrum' },
  { norwegian: 'ubetinget', english: 'unconditional' },
  { norwegian: 'validitet', english: 'validity' },
  { norwegian: 'abstrakt', english: 'abstract' },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'dialektikk', english: 'dialectic' },
  { norwegian: 'ekstrapolere', english: 'extrapolate' },
  { norwegian: 'forskrift', english: 'regulation' },
  { norwegian: 'gjennomførbarhet', english: 'feasibility' },
  { norwegian: 'ansvarlig', english: 'responsible' },
  { norwegian: 'bekreftelse', english: 'confirmation' },
  { norwegian: 'forutsetning', english: 'assumption' },
  { norwegian: 'tilnærming', english: 'approach' },
  { norwegian: 'utfordring', english: 'challenge' },
  { norwegian: 'vedvarende', english: 'persistent' },
  { norwegian: 'oppnåelse', english: 'achievement' },
  { norwegian: 'betydelig', english: 'significant' },
  { norwegian: 'tilstrekkelig', english: 'sufficient' },
  { norwegian: 'innflytelse', english: 'influence' },
  { norwegian: 'omstendighet', english: 'circumstance' },
  { norwegian: 'foreløpig', english: 'preliminary' },
  { norwegian: 'iverksette', english: 'implement' },
  { norwegian: 'samvittighet', english: 'conscience' },
  { norwegian: 'målrettet', english: 'targeted' },
  { norwegian: 'anerkjennelse', english: 'recognition' },
  { norwegian: 'tilfeldig', english: 'random' },
  { norwegian: 'gjennomføring', english: 'execution' },
  { norwegian: 'tilgjengelig', english: 'available' },
  { norwegian: 'forpliktelse', english: 'commitment' },
  { norwegian: 'nøyaktighet', english: 'accuracy' },
  { norwegian: 'samtidig', english: 'simultaneous' },
  { norwegian: 'innovasjon', english: 'innovation' },
  { norwegian: 'motivasjon', english: 'motivation' },
  { norwegian: 'forbedring', english: 'improvement' },
  { norwegian: 'strategisk', english: 'strategic' },
  { norwegian: 'engasjement', english: 'engagement' },
  { norwegian: 'fleksibel', english: 'flexible' },
  { norwegian: 'integritet', english: 'integrity' },
  { norwegian: 'evaluering', english: 'evaluation' },
  { norwegian: 'konsistens', english: 'consistency' },
  { norwegian: 'autentisitet', english: 'authenticity' },
  { norwegian: 'tilpasning', english: 'adaptation' },
  { norwegian: 'resiliens', english: 'resilience' },
  { norwegian: 'transparent', english: 'transparent' },
  { norwegian: 'initiativ', english: 'initiative' },
  { norwegian: 'perspektiv', english: 'perspective' },
  { norwegian: 'prioritering', english: 'prioritization' },
  { norwegian: 'synergier', english: 'synergies' },
  { norwegian: 'autonomi', english: 'autonomy' },
  { norwegian: 'kollaborativ', english: 'collaborative' },
  { norwegian: 'proaktiv', english: 'proactive' },
  { norwegian: 'dynamisk', english: 'dynamic' },
  { norwegian: 'effektivitet', english: 'efficiency' },
  { norwegian: 'innovativ', english: 'innovative' },
  { norwegian: 'multifasettert', english: 'multifaceted' },
  { norwegian: 'nettverk', english: 'network' },
  { norwegian: 'omstillingsdyktig', english: 'adaptable' },
  { norwegian: 'resonans', english: 'resonance' },
  { norwegian: 'visjonær', english: 'visionary' },
  { norwegian: 'anskaffelse', english: 'acquisition' },
  { norwegian: 'begrunnelse', english: 'justification' },
  { norwegian: 'komponent', english: 'component' },
  { norwegian: 'diversifisering', english: 'diversification' },
  { norwegian: 'effektivisering', english: 'streamlining' },
  { norwegian: 'forankring', english: 'anchoring' },
  { norwegian: 'gjennombrudd', english: 'breakthrough' },
  { norwegian: 'holdbarhet', english: 'durability' },
  { norwegian: 'intuisjon', english: 'intuition' },
  { norwegian: 'jevnaldrende', english: 'peer' },
  { norwegian: 'kunnskapsrik', english: 'knowledgeable' },
  { norwegian: 'legitimasjon', english: 'legitimation' },
  { norwegian: 'mestring', english: 'mastery' },
  { norwegian: 'nyskapning', english: 'innovation' },
  { norwegian: 'opphav', english: 'origin' },
  { norwegian: 'pålitelighet', english: 'reliability' },
  { norwegian: 'kvantifisere', english: 'quantify' },
  { norwegian: 'ressurser', english: 'resources' },
  { norwegian: 'samarbeid', english: 'collaboration' },
  { norwegian: 'tilbakemelding', english: 'feedback' },
  { norwegian: 'undersøkelse', english: 'investigation' },
  { norwegian: 'verdsettelse', english: 'valuation' },
  { norwegian: 'åpenbaring', english: 'revelation' },
  { norwegian: 'bistand', english: 'assistance' },
  { norwegian: 'konsekvens', english: 'consequence' },
  { norwegian: 'dialog', english: 'dialogue' },
  { norwegian: 'etablering', english: 'establishment' },
  { norwegian: 'fornyelse', english: 'renewal' },
  { norwegian: 'gjenoppretting', english: 'restoration' },
  { norwegian: 'harmoni', english: 'harmony' },
  { norwegian: 'innovasjonskapasitet', english: 'innovation capacity' },
  { norwegian: 'juridisk', english: 'legal' },
  { norwegian: 'kreativitet', english: 'creativity' },
  { norwegian: 'langsiktig', english: 'long-term' },
  { norwegian: 'mobilitet', english: 'mobility' },
  { norwegian: 'nøytralitet', english: 'neutrality' },
  { norwegian: 'optimalisering', english: 'optimization' },
  { norwegian: 'prosess', english: 'process' },
  { norwegian: 'kvalitativ', english: 'qualitative' },
  { norwegian: 'risikovurdering', english: 'risk assessment' },
  { norwegian: 'stabilitet', english: 'stability' },
  { norwegian: 'teoretisk', english: 'theoretical' },
  { norwegian: 'utvikling', english: 'development' },
  { norwegian: 'vitalitet', english: 'vitality' },
  { norwegian: 'arbeidsmoral', english: 'work ethic' },
  { norwegian: 'besluttsomhet', english: 'decisiveness' },
  { norwegian: 'kulturell bevissthet', english: 'cultural awareness' },
  { norwegian: 'lederskap', english: 'leadership' },
  { norwegian: 'meningsfull', english: 'meaningful' },
  { norwegian: 'reise', english: 'travel' },
  { norwegian: 'jobb', english: 'job' },
  { norwegian: 'venn', english: 'friend' },
  { norwegian: 'familie', english: 'family' },
  { norwegian: 'hjem', english: 'home' },
  { norwegian: 'skole', english: 'school' },
  { norwegian: 'mat', english: 'food' },
  { norwegian: 'drikke', english: 'drink' },
  { norwegian: 'by', english: 'city' },
  { norwegian: 'land', english: 'country' },
  { norwegian: 'språk', english: 'language' },
  { norwegian: 'hus', english: 'house' },
  { norwegian: 'leilighet', english: 'apartment' },
  { norwegian: 'butikk', english: 'store, shop' },
  { norwegian: 'restaurant', english: 'restaurant' },
  { norwegian: 'hotell', english: 'hotel' },
  { norwegian: 'stasjon', english: 'station' },
  { norwegian: 'flyplass', english: 'airport' },
  { norwegian: 'bil', english: 'car' },
  { norwegian: 'tog', english: 'train' },
  { norwegian: 'buss', english: 'bus' },
  { norwegian: 'gate', english: 'street' },
  { norwegian: 'vei', english: 'road' },
  { norwegian: 'bro', english: 'bridge' },
  { norwegian: 'park', english: 'park' },
  { norwegian: 'skog', english: 'forest' },
  { norwegian: 'strand', english: 'beach' },
  { norwegian: 'elv', english: 'river' },
  { norwegian: 'sjø', english: 'sea' },
  { norwegian: 'innsjø', english: 'lake' },
  { norwegian: 'fjell', english: 'mountain' },
  { norwegian: 'vær', english: 'weather' },
  { norwegian: 'sol', english: 'sun' },
  { norwegian: 'regn', english: 'rain' },
  { norwegian: 'snø', english: 'snow' },
  { norwegian: 'vind', english: 'wind' },
  { norwegian: 'sky', english: 'cloud' },
  { norwegian: 'temperatur', english: 'temperature' },
  { norwegian: 'kald', english: 'cold' },
  { norwegian: 'varm', english: 'warm' },
  { norwegian: 'het', english: 'hot' },
  { norwegian: 'kjølig', english: 'cool' },
  { norwegian: 'fryse', english: 'freeze' },
  { norwegian: 'kjærlighet', english: 'love' },
  { norwegian: 'lykke', english: 'happiness' },
  { norwegian: 'sorg', english: 'sorrow' },
  { norwegian: 'følelse', english: 'feeling' },
  { norwegian: 'tanker', english: 'thoughts' },
  { norwegian: 'erfaring', english: 'experience' },
  { norwegian: 'drøm', english: 'dream' },
  { norwegian: 'evig', english: 'eternal' },
  { norwegian: 'tviler', english: 'doubt' },
  { norwegian: 'på sett og vis', english: 'in a way' },
  { norwegian: 'ærlig talt', english: 'honestly' },
  { norwegian: 'uendelig', english: 'infinite' },
  { norwegian: 'i stand til', english: 'able to' },
  { norwegian: 'med mindre', english: 'unless' },
  { norwegian: 'neppe', english: 'hardly' },
  { norwegian: 'foreta', english: 'undertake' },
  { norwegian: 'bestandig', english: 'always' },
  { norwegian: 'i den grad', english: 'to the extent' },
  { norwegian: 'rett og slett', english: 'simply' },
  { norwegian: 'som følge', english: 'as a result' },
  { norwegian: 'tyder på', english: 'indicate' },
  { norwegian: 'bærekraftig', english: 'sustainable' },
  { norwegian: 'globalisering', english: 'globalization' },
  { norwegian: 'innovasjon', english: 'innovation' },
  { norwegian: 'kunstig intelligens', english: 'artificial intelligence' },
  { norwegian: 'multikulturalisme', english: 'multiculturalism' },
  { norwegian: 'pandemi', english: 'pandemic' },
  { norwegian: 'resiliens', english: 'resilience' },
  { norwegian: 'samfunnsansvar', english: 'corporate social responsibility' },
  { norwegian: 'teknologisk fremskritt', english: 'technological advancement' },
  { norwegian: 'urbanisering', english: 'urbanization' },
  { norwegian: 'velferdsstat', english: 'welfare state' },
  { norwegian: 'ytringsfrihet', english: 'freedom of speech' },
  { norwegian: 'etikk', english: 'ethics' },
  { norwegian: 'fornybar energi', english: 'renewable energy' },
  { norwegian: 'geopolitikk', english: 'geopolitics' },
  { norwegian: 'humanitær intervensjon', english: 'humanitarian intervention' },
  { norwegian: 'integrering', english: 'integration' },
  { norwegian: 'juridisk', english: 'legal' },
  { norwegian: 'kryptokurver', english: 'cryptocurrencies' },
  { norwegian: 'langsiktig', english: 'long-term' },
  { norwegian: 'menneskerettigheter', english: 'human rights' },
  { norwegian: 'naturvern', english: 'conservation' },
  { norwegian: 'oppsving', english: 'upswing' },
  { norwegian: 'politisk stabilitet', english: 'political stability' },
  { norwegian: 'kvantitativ', english: 'quantitative' },
  { norwegian: 'risikostyring', english: 'risk management' },
  { norwegian: 'sosial ulikhet', english: 'social inequality' },
  { norwegian: 'transparens', english: 'transparency' },
  { norwegian: 'ulikhet', english: 'inequality' },
  { norwegian: 'verdensøkonomi', english: 'world economy' },
  { norwegian: 'åpen kildekode', english: 'open source' },
  { norwegian: 'digitalisering', english: 'digitalization' },
  { norwegian: 'ekstremvær', english: 'extreme weather' },
  { norwegian: 'finansiell inkludering', english: 'financial inclusion' },
  { norwegian: 'grønn teknologi', english: 'green technology' },
  { norwegian: 'helseteknologi', english: 'health technology' },
  { norwegian: 'immaterielle rettigheter', english: 'intellectual property rights' },
  { norwegian: 'klimaendringer', english: 'climate change' },
  { norwegian: 'lederskap', english: 'leadership' },
  { norwegian: 'mikrofinans', english: 'microfinance' },
  { norwegian: 'nyskaping', english: 'innovation' },
  { norwegian: 'omstillingsdyktig', english: 'adaptable' },
  { norwegian: 'proaktiv', english: 'proactive' },
  { norwegian: 'ressursforvaltning', english: 'resource management' },
  { norwegian: 'samfunnsvitenskap', english: 'social science' },
  { norwegian: 'teknologisk disrupsjon', english: 'technological disruption' },
  { norwegian: 'utviklingspolitikk', english: 'development policy' },
  { norwegian: 'virkelighetsoppfatning', english: 'perception of reality' },
  { norwegian: 'økonomisk bærekraft', english: 'economic sustainability' },
  { norwegian: 'å analysere', english: 'to analyze' },
  { norwegian: 'å argumentere', english: 'to argue' },
  { norwegian: 'å bidra', english: 'to contribute' },
  { norwegian: 'å betrakte', english: 'to consider' },
  { norwegian: 'å bevise', english: 'to prove' },
  { norwegian: 'å diskutere', english: 'to discuss' },
  { norwegian: 'å evaluere', english: 'to evaluate' },
  { norwegian: 'å forbedre', english: 'to improve' },
  { norwegian: 'å forhandle', english: 'to negotiate' },
  { norwegian: 'å formidle', english: 'to convey' },
  { norwegian: 'å forskjønne', english: 'to embellish' },
  { norwegian: 'å forstå', english: 'to understand' },
  { norwegian: 'å forutse', english: 'to anticipate' },
  { norwegian: 'å fremheve', english: 'to highlight' },
  { norwegian: 'å gjennomføre', english: 'to implement' },
  { norwegian: 'å gjenspeile', english: 'to reflect' },
  { norwegian: 'å granske', english: 'to investigate' },
  { norwegian: 'å handle', english: 'to act' },
  { norwegian: 'å identifisere', english: 'to identify' },
  { norwegian: 'å innovere', english: 'to innovate' },
  { norwegian: 'å integrere', english: 'to integrate' },
  { norwegian: 'å kritisere', english: 'to criticize' },
  { norwegian: 'å lede', english: 'to lead' },
  { norwegian: 'å løse', english: 'to solve' },
  { norwegian: 'å mediere', english: 'to mediate' },
  { norwegian: 'å observere', english: 'to observe' },
  { norwegian: 'å oppnå', english: 'to achieve' },
  { norwegian: 'å opprettholde', english: 'to maintain' },
  { norwegian: 'å overbevise', english: 'to convince' },
  { norwegian: 'å overvinne', english: 'to overcome' },
  { norwegian: 'å påvirke', english: 'to influence' },
  { norwegian: 'å reflektere', english: 'to reflect' },
  { norwegian: 'å regulere', english: 'to regulate' },
  { norwegian: 'å relatere', english: 'to relate' },
  { norwegian: 'å representere', english: 'to represent' },
  { norwegian: 'å resonnere', english: 'to reason' },
  { norwegian: 'å respektere', english: 'to respect' },
  { norwegian: 'å revidere', english: 'to revise' },
  { norwegian: 'å sammenligne', english: 'to compare' },
  { norwegian: 'å samtykke', english: 'to consent' },
  { norwegian: 'å simulere', english: 'to simulate' },
  { norwegian: 'å spesifisere', english: 'to specify' },
  { norwegian: 'å stimulere', english: 'to stimulate' },
  { norwegian: 'å tolke', english: 'to interpret' },
  { norwegian: 'å transformere', english: 'to transform' },
  { norwegian: 'å utforske', english: 'to explore' },
  { norwegian: 'å utforme', english: 'to design' },
  { norwegian: 'å utvikle', english: 'to develop' },
  { norwegian: 'å vurdere', english: 'to assess' },
  { norwegian: 'å øke', english: 'to increase' },
  { norwegian: 'å akseptere', english: 'to accept' },
  { norwegian: 'å anbefale', english: 'to recommend' },
  { norwegian: 'å arrangere', english: 'to arrange' },
  { norwegian: 'å avsløre', english: 'to reveal' },
  { norwegian: 'å behandle', english: 'to treat' },
  { norwegian: 'å beskrive', english: 'to describe' },
  { norwegian: 'å bestemme', english: 'to decide' },
  { norwegian: 'å bevare', english: 'to preserve' },
  { norwegian: 'å delta', english: 'to participate' },
  { norwegian: 'å diskutere', english: 'to discuss' },
  { norwegian: 'å eksistere', english: 'to exist' },
  { norwegian: 'å forklare', english: 'to explain' },
  { norwegian: 'å forlate', english: 'to leave' },
  { norwegian: 'å forstå', english: 'to understand' },
  { norwegian: 'å fortelle', english: 'to tell' },
  { norwegian: 'å fremstå', english: 'to appear' },
  { norwegian: 'å fylle', english: 'to fill' },
  { norwegian: 'å gjelde', english: 'to apply' },
  { norwegian: 'å gjennomføre', english: 'to carry out' },
  { norwegian: 'å gråte', english: 'to cry' },
  { norwegian: 'å håpe', english: 'to hope' },
  { norwegian: 'å huske', english: 'to remember' },
  { norwegian: 'å inkludere', english: 'to include' },
  { norwegian: 'å innrømme', english: 'to admit' },
  { norwegian: 'å kjempe', english: 'to fight' },
  { norwegian: 'å klare', english: 'to manage' },
  { norwegian: 'å kombinere', english: 'to combine' },
  { norwegian: 'å kommentere', english: 'to comment' },
  { norwegian: 'å kontakte', english: 'to contact' },
  { norwegian: 'å kritisere', english: 'to criticize' },
  { norwegian: 'å le', english: 'to laugh' },
  { norwegian: 'å levere', english: 'to deliver' },
  { norwegian: 'å like', english: 'to like' },
  { norwegian: 'å lykkes', english: 'to succeed' },
  { norwegian: 'å møte', english: 'to meet' },
  { norwegian: 'å nevne', english: 'to mention' },
  { norwegian: 'å observere', english: 'to observe' },
  { norwegian: 'å oppdage', english: 'to discover' },
  { norwegian: 'å oppleve', english: 'to experience' },
  { norwegian: 'å oppnå', english: 'to achieve' },
  { norwegian: 'å organisere', english: 'to organize' },
  { norwegian: 'å planlegge', english: 'to plan' },
  { norwegian: 'å presentere', english: 'to present' },
  { norwegian: 'å reagere', english: 'to react' },
  { norwegian: 'å reise', english: 'to travel' },
  { norwegian: 'å respektere', english: 'to respect' },
  { norwegian: 'å skape', english: 'to create' },
  { norwegian: 'å studere', english: 'to study' },
  { norwegian: 'å tenke', english: 'to think' },
  { norwegian: 'å uttrykke', english: 'to express' },
  { norwegian: 'å velge', english: 'to choose' },
  { norwegian: 'å arbeide', english: 'to work' },
  { norwegian: 'å begynne', english: 'to begin' },
  { norwegian: 'å besøke', english: 'to visit' },
  { norwegian: 'å betale', english: 'to pay' },
  { norwegian: 'å bo', english: 'to live' },
  { norwegian: 'å bry', english: 'to care' },
  { norwegian: 'å dra', english: 'to go' },
  { norwegian: 'å drikke', english: 'to drink' },
  { norwegian: 'å elske', english: 'to love' },
  { norwegian: 'å finne', english: 'to find' },
  { norwegian: 'å forlate', english: 'to leave' },
  { norwegian: 'å forstå', english: 'to understand' },
  { norwegian: 'å få', english: 'to receive' },
  { norwegian: 'å gi', english: 'to give' },
  { norwegian: 'å gå', english: 'to walk' },
  { norwegian: 'å ha', english: 'to have' },
  { norwegian: 'å hate', english: 'to hate' },
  { norwegian: 'å hjelpe', english: 'to help' },
  { norwegian: 'å høre', english: 'to hear' },
  { norwegian: 'å kjøpe', english: 'to buy' },
  { norwegian: 'å komme', english: 'to come' },
  { norwegian: 'å kunne', english: 'to be able to' },
  { norwegian: 'å le', english: 'to laugh' },
  { norwegian: 'å leke', english: 'to play' },
  { norwegian: 'å lese', english: 'to read' },
  { norwegian: 'å like', english: 'to like' },
  { norwegian: 'å lytte', english: 'to listen' },
  { norwegian: 'å lage', english: 'to make' },
  { norwegian: 'å miste', english: 'to lose' },
  { norwegian: 'å motta', english: 'to receive' },
  { norwegian: 'å måtte', english: 'to have to' },
  { norwegian: 'å reise', english: 'to travel' },
  { norwegian: 'å ringe', english: 'to call' },
  { norwegian: 'å si', english: 'to say' },
  { norwegian: 'å se', english: 'to see' },
  { norwegian: 'å selge', english: 'to sell' },
  { norwegian: 'å sende', english: 'to send' },
  { norwegian: 'å sette', english: 'to put' },
  { norwegian: 'å sitte', english: 'to sit' },
  { norwegian: 'å skjønne', english: 'to understand' },
  { norwegian: 'å skrive', english: 'to write' },
  { norwegian: 'å snakke', english: 'to talk' },
  { norwegian: 'å sove', english: 'to sleep' },
  { norwegian: 'å spille', english: 'to play' },
  { norwegian: 'å spise', english: 'to eat' },
  { norwegian: 'å stå', english: 'to stand' },
  { norwegian: 'å studere', english: 'to study' },
  { norwegian: 'å synge', english: 'to sing' },
  { norwegian: 'å ta', english: 'to take' },
  { norwegian: 'å tenke', english: 'to think' },
  { norwegian: 'å ville', english: 'to want' },
  { norwegian: 'å avhenge', english: 'to depend' },
  { norwegian: 'å berike', english: 'to enrich' },
  { norwegian: 'å dedusere', english: 'to deduce' },
  { norwegian: 'å differensiere', english: 'to differentiate' },
  { norwegian: 'å eliminere', english: 'to eliminate' },
  { norwegian: 'å engasjere', english: 'to engage' },
  { norwegian: 'å etablere', english: 'to establish' },
  { norwegian: 'å evaluere', english: 'to evaluate' },
  { norwegian: 'å forankre', english: 'to anchor' },
  { norwegian: 'å forbli', english: 'to remain' },
  { norwegian: 'å forutsi', english: 'to predict' },
  { norwegian: 'å fremme', english: 'to promote' },
  { norwegian: 'å fjerne', english: 'to remove' },
  { norwegian: 'å generere', english: 'to generate' },
  { norwegian: 'å godkjenne', english: 'to approve' },
  { norwegian: 'å harmonisere', english: 'to harmonize' },
  { norwegian: 'å implementere', english: 'to implement' },
  { norwegian: 'å improvisere', english: 'to improvise' },
  { norwegian: 'å inkludere', english: 'to include' },
  { norwegian: 'å insistere', english: 'to insist' },
  { norwegian: 'å integrere', english: 'to integrate' },
  { norwegian: 'å intensivere', english: 'to intensify' },
  { norwegian: 'å intervenere', english: 'to intervene' },
  { norwegian: 'å kategorisere', english: 'to categorize' },
  { norwegian: 'å konsolidere', english: 'to consolidate' },
  { norwegian: 'å konvertere', english: 'to convert' },
  { norwegian: 'å koordinere', english: 'to coordinate' },
  { norwegian: 'å korrelere', english: 'to correlate' },
  { norwegian: 'å kritisere', english: 'to criticize' },
  { norwegian: 'å manipulere', english: 'to manipulate' },
  { norwegian: 'å maksimere', english: 'to maximize' },
  { norwegian: 'å minimere', english: 'to minimize' },
  { norwegian: 'å modifisere', english: 'to modify' },
  { norwegian: 'å navigere', english: 'to navigate' },
  { norwegian: 'å normalisere', english: 'to normalize' },
  { norwegian: 'å observere', english: 'to observe' },
  { norwegian: 'å optimalisere', english: 'to optimize' },
  { norwegian: 'å organisere', english: 'to organize' },
  { norwegian: 'å orientere', english: 'to orient' },
  { norwegian: 'å overgå', english: 'to surpass' },
  { norwegian: 'å overholde', english: 'to comply' },
  { norwegian: 'å oversette', english: 'to translate' },
  { norwegian: 'å prioritere', english: 'to prioritize' },
  { norwegian: 'å problematisere', english: 'to problematize' },
  { norwegian: 'å produsere', english: 'to produce' },
  { norwegian: 'å projisere', english: 'to project' },
  { norwegian: 'å promotere', english: 'to promote' },
  { norwegian: 'å reformere', english: 'to reform' },
  { norwegian: 'å regulere', english: 'to regulate' },
  { norwegian: 'å relatere', english: 'to relate' },
  { norwegian: 'å anerkjenne', english: 'to acknowledge' },
  { norwegian: 'å ansette', english: 'to employ' },
  { norwegian: 'å avvise', english: 'to reject' },
  { norwegian: 'å beundre', english: 'to admire' },
  { norwegian: 'å bevise', english: 'to prove' },
  { norwegian: 'å bidra', english: 'to contribute' },
  { norwegian: 'å diskutere', english: 'to discuss' },
  { norwegian: 'å endre', english: 'to change' },
  { norwegian: 'å erfare', english: 'to experience' },
  { norwegian: 'å erklære', english: 'to declare' },
  { norwegian: 'å etterspørre', english: 'to request' },
  { norwegian: 'å forenkle', english: 'to simplify' },
  { norwegian: 'å foretrekke', english: 'to prefer' },
  { norwegian: 'å forklare', english: 'to explain' },
  { norwegian: 'å forlenge', english: 'to extend' },
  { norwegian: 'å fornye', english: 'to renew' },
  { norwegian: 'å forutsi', english: 'to predict' },
  { norwegian: 'å frykte', english: 'to fear' },
  { norwegian: 'å fylle', english: 'to fill' },
  { norwegian: 'å gjenskape', english: 'to recreate' },
  { norwegian: 'å gjenvinne', english: 'to regain' },
  { norwegian: 'å godta', english: 'to accept' },
  { norwegian: 'å gruble', english: 'to ponder' },
  { norwegian: 'å håndtere', english: 'to handle' },
  { norwegian: 'å hevde', english: 'to claim' },
  { norwegian: 'å hindre', english: 'to prevent' },
  { norwegian: 'å hyggje', english: 'to enjoy' },
  { norwegian: 'å ignorere', english: 'to ignore' },
  { norwegian: 'å imponere', english: 'to impress' },
  { norwegian: 'å innføre', english: 'to introduce' },
  { norwegian: 'å innrømme', english: 'to admit' },
  { norwegian: 'å inspirere', english: 'to inspire' },
  { norwegian: 'å instruere', english: 'to instruct' },
  { norwegian: 'å investere', english: 'to invest' },
  { norwegian: 'å invitere', english: 'to invite' },
  { norwegian: 'å justere', english: 'to adjust' },
  { norwegian: 'å klage', english: 'to complain' },
  { norwegian: 'å koble', english: 'to connect' },
  { norwegian: 'å konfrontere', english: 'to confront' },
  { norwegian: 'å konsentrere', english: 'to concentrate' },
  { norwegian: 'å konsumere', english: 'to consume' },
  { norwegian: 'å kontrollere', english: 'to control' },
  { norwegian: 'å kritisere', english: 'to criticize' },
  { norwegian: 'å lede', english: 'to lead' },
  { norwegian: 'å markere', english: 'to mark' },
  { norwegian: 'å merke', english: 'to notice' },
  { norwegian: 'å navigere', english: 'to navigate' },
  { norwegian: 'å nekte', english: 'to deny' },
  { norwegian: 'å observere', english: 'to observe' },
  { norwegian: 'å oppdage', english: 'to discover' },
  { norwegian: 'å ankomme', english: 'to arrive' },
  { norwegian: 'å avslutte', english: 'to finish' },
  { norwegian: 'å besøke', english: 'to visit' },
  { norwegian: 'å bestille', english: 'to order' },
  { norwegian: 'å betale', english: 'to pay' },
  { norwegian: 'å bære', english: 'to carry' },
  { norwegian: 'å danse', english: 'to dance' },
  { norwegian: 'å dele', english: 'to share' },
  { norwegian: 'å drømme', english: 'to dream' },
  { norwegian: 'å eie', english: 'to own' },
  { norwegian: 'å elske', english: 'to love' },
  { norwegian: 'å erindre', english: 'to remember' },
  { norwegian: 'å falle', english: 'to fall' },
  { norwegian: 'å feste', english: 'to party' },
  { norwegian: 'å finne', english: 'to find' },
  { norwegian: 'å fly', english: 'to fly' },
  { norwegian: 'å flytte', english: 'to move' },
  { norwegian: 'å følge', english: 'to follow' },
  { norwegian: 'å gråte', english: 'to cry' },
  { norwegian: 'å gjemme', english: 'to hide' },
  { norwegian: 'å gjøre', english: 'to do' },
  { norwegian: 'å glede', english: 'to please' },
  { norwegian: 'å håpe', english: 'to hope' },
  { norwegian: 'å hate', english: 'to hate' },
  { norwegian: 'å heve', english: 'to raise' },
  { norwegian: 'å hoppe', english: 'to jump' },
  { norwegian: 'å høre', english: 'to hear' },
  { norwegian: 'å invitere', english: 'to invite' },
  { norwegian: 'å kjøre', english: 'to drive' },
  { norwegian: 'å klatre', english: 'to climb' },
  { norwegian: 'å kjenne', english: 'to know' },
  { norwegian: 'å le', english: 'to smile' },
  { norwegian: 'å lære', english: 'to learn' },
  { norwegian: 'å løpe', english: 'to run' },
  { norwegian: 'å male', english: 'to paint' },
  { norwegian: 'å mene', english: 'to mean' },
  { norwegian: 'å nyte', english: 'to enjoy' },
  { norwegian: 'å passe', english: 'to fit' },
  { norwegian: 'å prøve', english: 'to try' },
  { norwegian: 'å puste', english: 'to breathe' },
  { norwegian: 'å reise', english: 'to travel' },
  { norwegian: 'å rope', english: 'to shout' },
  { norwegian: 'å savne', english: 'to miss' },
  { norwegian: 'å selge', english: 'to sell' },
  { norwegian: 'å sende', english: 'to send' },
  { norwegian: 'å synes', english: 'to think' },
  { norwegian: 'å treffe', english: 'to meet' },
  { norwegian: 'å tro', english: 'to believe' },
  { norwegian: 'å vente', english: 'to wait' },
  { norwegian: 'å ønske', english: 'to wish' },
  { norwegian: 'skyld', english: 'fault' },
  { norwegian: 'svelge', english: 'swallow' },
  { norwegian: 'lysne', english: 'brighten' },
  { norwegian: 'klare seg', english: 'manage' },
  { norwegian: 'ete', english: 'eat' },
  { norwegian: 'stall', english: 'stable' },
  { norwegian: 'hvile', english: 'rest' },
  { norwegian: 'så klart', english: 'of course' },
  { norwegian: 'gnir', english: 'rubs' },
  { norwegian: 'fang', english: 'lap' },
  { norwegian: 'ekkel', english: 'nasty' },
  { norwegian: 'å tasse', english: 'to paw' },
  { norwegian: 'skyld', english: 'fault' },
  { norwegian: 'å utfolde', english: 'to unfold' },
  { norwegian: 'å forholde', english: 'to relate' },
  { norwegian: 'tvert imot', english: 'On the contrary' },
  { norwegian: 'å plage', english: 'to annoy' },
  { norwegian: 'halsen', english: 'throat' },
  { norwegian: 'demper', english: 'dampens' },
  { norwegian: 'lurer meg', english: 'tricks me' },
  { norwegian: 'strengt', english: 'strictly' },
  { norwegian: 'avtar', english: 'decreases' },
  { norwegian: 'kjenne', english: 'feel' },
  { norwegian: 'betraktelig', english: 'considerably' },
  { norwegian: 'minsker', english: 'decreases' },
  { norwegian: 'befriende', english: 'liberating' },
  { norwegian: 'foreta meg', english: 'make me' },
  { norwegian: 'merkelig', english: 'strange' },
  { norwegian: 'voldsomt', english: 'violently' },
  { norwegian: 'omtrent', english: 'approximately' },
  { norwegian: 'nevne', english: 'mention' },
  { norwegian: 'forberede', english: 'prepare' },
  { norwegian: 'å drøye', english: 'to linger' },
];
