// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NorskImport } from './routes/norsk'
import { Route as EnglishImport } from './routes/english'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NorskRoute = NorskImport.update({
  path: '/norsk',
  getParentRoute: () => rootRoute,
} as any)

const EnglishRoute = EnglishImport.update({
  path: '/english',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/english': {
      preLoaderRoute: typeof EnglishImport
      parentRoute: typeof rootRoute
    }
    '/norsk': {
      preLoaderRoute: typeof NorskImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  EnglishRoute,
  NorskRoute,
])
